-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [e02]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import examples.e02.translation.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open e02

/-- [anodized_logic::arithmetic::{impl core::ops::arith::Add<i32, anodized_logic::arithmetic::int> for anodized_logic::arithmetic::int}::add]:
    Source: '/cargo/git/checkouts/anodized-c4166da61bc74ac3/f7e8e56/crates/anodized-logic/src/arithmetic/interop.rs', lines 75:12-75:60
    Name pattern: [anodized_logic::arithmetic::{core::ops::arith::Add<anodized_logic::arithmetic::int, i32, anodized_logic::arithmetic::int>}::add]
    Visibility: public -/
@[rust_fun
  "anodized_logic::arithmetic::{core::ops::arith::Add<anodized_logic::arithmetic::int, i32, anodized_logic::arithmetic::int>}::add"]
axiom anodized_logic.arithmetic.int.Insts.CoreOpsArithAddI32int.add
  :
  anodized_logic.arithmetic.int → Std.I32 → Result
    anodized_logic.arithmetic.int

/-- [anodized_logic::arithmetic::{impl core::ops::arith::Div<i32, anodized_logic::arithmetic::int> for &'_0 anodized_logic::arithmetic::int}::div]:
    Source: '/cargo/git/checkouts/anodized-c4166da61bc74ac3/f7e8e56/crates/anodized-logic/src/arithmetic/interop.rs', lines 151:12-151:60
    Name pattern: [anodized_logic::arithmetic::{core::ops::arith::Div<&'0 anodized_logic::arithmetic::int, i32, anodized_logic::arithmetic::int>}::div]
    Visibility: public -/
@[rust_fun
  "anodized_logic::arithmetic::{core::ops::arith::Div<&'0 anodized_logic::arithmetic::int, i32, anodized_logic::arithmetic::int>}::div"]
axiom Shared0int.Insts.CoreOpsArithDivI32int.div
  :
  anodized_logic.arithmetic.int → Std.I32 → Result
    anodized_logic.arithmetic.int

/-- [anodized_logic::arithmetic::{impl core::ops::arith::Rem<i32, anodized_logic::arithmetic::int> for &'_0 anodized_logic::arithmetic::int}::rem]:
    Source: '/cargo/git/checkouts/anodized-c4166da61bc74ac3/f7e8e56/crates/anodized-logic/src/arithmetic/interop.rs', lines 160:12-160:60
    Name pattern: [anodized_logic::arithmetic::{core::ops::arith::Rem<&'0 anodized_logic::arithmetic::int, i32, anodized_logic::arithmetic::int>}::rem]
    Visibility: public -/
@[rust_fun
  "anodized_logic::arithmetic::{core::ops::arith::Rem<&'0 anodized_logic::arithmetic::int, i32, anodized_logic::arithmetic::int>}::rem"]
axiom Shared0int.Insts.CoreOpsArithRemI32int.rem
  :
  anodized_logic.arithmetic.int → Std.I32 → Result
    anodized_logic.arithmetic.int

/-- [anodized_logic::arithmetic::{impl core::ops::arith::Mul<&'_0 anodized_logic::arithmetic::int, anodized_logic::arithmetic::int> for i32}::mul]:
    Source: '/cargo/git/checkouts/anodized-c4166da61bc74ac3/f7e8e56/crates/anodized-logic/src/arithmetic/interop.rs', lines 187:12-187:82
    Name pattern: [anodized_logic::arithmetic::{core::ops::arith::Mul<i32, &'0 anodized_logic::arithmetic::int, anodized_logic::arithmetic::int>}::mul]
    Visibility: public -/
@[rust_fun
  "anodized_logic::arithmetic::{core::ops::arith::Mul<i32, &'0 anodized_logic::arithmetic::int, anodized_logic::arithmetic::int>}::mul"]
axiom I32.Insts.CoreOpsArithMulShared0intint.mul
  :
  Std.I32 → anodized_logic.arithmetic.int → Result
    anodized_logic.arithmetic.int

/-- [anodized_logic::arithmetic::{impl core::cmp::PartialEq<i32> for anodized_logic::arithmetic::int}::eq]:
    Source: '/cargo/git/checkouts/anodized-c4166da61bc74ac3/f7e8e56/crates/anodized-logic/src/arithmetic/interop.rs', lines 223:12-223:44
    Name pattern: [anodized_logic::arithmetic::{core::cmp::PartialEq<anodized_logic::arithmetic::int, i32>}::eq]
    Visibility: public -/
@[rust_fun
  "anodized_logic::arithmetic::{core::cmp::PartialEq<anodized_logic::arithmetic::int, i32>}::eq"]
axiom anodized_logic.arithmetic.int.Insts.CoreCmpPartialEqI32.eq
  : anodized_logic.arithmetic.int → Std.I32 → Result Bool

/-- [anodized_logic::arithmetic::{impl core::cmp::PartialOrd<i32> for anodized_logic::arithmetic::int}::gt]:
    Source: '/cargo/git/checkouts/anodized-c4166da61bc74ac3/f7e8e56/crates/anodized-logic/src/arithmetic/interop.rs', lines 239:8-239:68
    Name pattern: [anodized_logic::arithmetic::{core::cmp::PartialOrd<anodized_logic::arithmetic::int, i32>}::gt]
    Visibility: public -/
@[rust_fun
  "anodized_logic::arithmetic::{core::cmp::PartialOrd<anodized_logic::arithmetic::int, i32>}::gt"]
axiom anodized_logic.arithmetic.int.Insts.CoreCmpPartialOrdI32.gt
  : anodized_logic.arithmetic.int → Std.I32 → Result Bool

