-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [e02]: function definitions
import Aeneas
import examples.e02.translation.Types
import examples.e02.translation.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace e02

/-- [e02::__anodized_fn_requires_collatz::{impl core::ops::function::Fn<(), bool> for e02::__anodized_fn_requires_collatz::closure<'_0>}::call]:
    Source: 'examples/e02/src/lib.rs', lines 4:0-7:2 -/
def
  __anodized_fn_requires_collatz.closure.Insts.CoreOpsFunctionFnTupleBool.call
  (c : __anodized_fn_requires_collatz.closure) (_ : Unit) : Result Bool := do
  anodized_logic.arithmetic.int.Insts.CoreCmpPartialOrdI32.gt c 0#i32

/-- [e02::__anodized_fn_requires_collatz::{impl core::ops::function::FnMut<(), bool> for e02::__anodized_fn_requires_collatz::closure<'_0>}::call_mut]:
    Source: 'examples/e02/src/lib.rs', lines 4:0-7:2 -/
def
  __anodized_fn_requires_collatz.closure.Insts.CoreOpsFunctionFnMutTupleBool.call_mut
  (state : __anodized_fn_requires_collatz.closure) (_ : Unit) :
  Result (Bool × __anodized_fn_requires_collatz.closure)
  := do
  let b ←
    __anodized_fn_requires_collatz.closure.Insts.CoreOpsFunctionFnTupleBool.call
      state ()
  ok (b, state)

/-- [e02::__anodized_fn_requires_collatz::{impl core::ops::function::FnOnce<(), bool> for e02::__anodized_fn_requires_collatz::closure<'_0>}::call_once]:
    Source: 'examples/e02/src/lib.rs', lines 4:0-7:2 -/
def
  __anodized_fn_requires_collatz.closure.Insts.CoreOpsFunctionFnOnceTupleBool.call_once
  (c : __anodized_fn_requires_collatz.closure) (_ : Unit) : Result Bool := do
  let (b, _) ←
    __anodized_fn_requires_collatz.closure.Insts.CoreOpsFunctionFnMutTupleBool.call_mut
      c ()
  ok b

/-- Trait implementation: [e02::__anodized_fn_requires_collatz::{impl core::ops::function::FnOnce<(), bool> for e02::__anodized_fn_requires_collatz::closure<'_0>}]
    Source: 'examples/e02/src/lib.rs', lines 4:0-7:2 -/
@[reducible]
def __anodized_fn_requires_collatz.closure.Insts.CoreOpsFunctionFnOnceTupleBool
  : core.ops.function.FnOnce __anodized_fn_requires_collatz.closure Unit Bool
  := {
  call_once :=
    __anodized_fn_requires_collatz.closure.Insts.CoreOpsFunctionFnOnceTupleBool.call_once
}

/-- Trait implementation: [e02::__anodized_fn_requires_collatz::{impl core::ops::function::FnMut<(), bool> for e02::__anodized_fn_requires_collatz::closure<'_0>}]
    Source: 'examples/e02/src/lib.rs', lines 4:0-7:2 -/
@[reducible]
def __anodized_fn_requires_collatz.closure.Insts.CoreOpsFunctionFnMutTupleBool
  : core.ops.function.FnMut __anodized_fn_requires_collatz.closure Unit Bool
  := {
  FnOnceInst :=
    __anodized_fn_requires_collatz.closure.Insts.CoreOpsFunctionFnOnceTupleBool
  call_mut :=
    __anodized_fn_requires_collatz.closure.Insts.CoreOpsFunctionFnMutTupleBool.call_mut
}

/-- Trait implementation: [e02::__anodized_fn_requires_collatz::{impl core::ops::function::Fn<(), bool> for e02::__anodized_fn_requires_collatz::closure<'_0>}]
    Source: 'examples/e02/src/lib.rs', lines 4:0-7:2 -/
@[reducible]
def __anodized_fn_requires_collatz.closure.Insts.CoreOpsFunctionFnTupleBool :
  core.ops.function.Fn __anodized_fn_requires_collatz.closure Unit Bool := {
  FnMutInst :=
    __anodized_fn_requires_collatz.closure.Insts.CoreOpsFunctionFnMutTupleBool
  call :=
    __anodized_fn_requires_collatz.closure.Insts.CoreOpsFunctionFnTupleBool.call
}

/-- [e02::__anodized_fn_ensures_collatz::{impl core::ops::function::Fn<(&'_ anodized_logic::arithmetic::int,), bool> for e02::__anodized_fn_ensures_collatz::closure}::call]:
    Source: 'examples/e02/src/lib.rs', lines 4:0-7:2 -/
def
  __anodized_fn_ensures_collatz.closure.Insts.CoreOpsFunctionFnTupleSharedintBool.call
  (c : __anodized_fn_ensures_collatz.closure)
  (tupled_args : anodized_logic.arithmetic.int) :
  Result Bool
  := do
  anodized_logic.arithmetic.int.Insts.CoreCmpPartialEqI32.eq tupled_args 1#i32

/-- [e02::__anodized_fn_ensures_collatz::{impl core::ops::function::FnMut<(&'_ anodized_logic::arithmetic::int,), bool> for e02::__anodized_fn_ensures_collatz::closure}::call_mut]:
    Source: 'examples/e02/src/lib.rs', lines 4:0-7:2 -/
def
  __anodized_fn_ensures_collatz.closure.Insts.CoreOpsFunctionFnMutTupleSharedintBool.call_mut
  (state : __anodized_fn_ensures_collatz.closure)
  (args : anodized_logic.arithmetic.int) :
  Result (Bool × __anodized_fn_ensures_collatz.closure)
  := do
  let b ←
    __anodized_fn_ensures_collatz.closure.Insts.CoreOpsFunctionFnTupleSharedintBool.call
      state args
  ok (b, state)

/-- [e02::__anodized_fn_ensures_collatz::{impl core::ops::function::FnOnce<(&'_ anodized_logic::arithmetic::int,), bool> for e02::__anodized_fn_ensures_collatz::closure}::call_once]:
    Source: 'examples/e02/src/lib.rs', lines 4:0-7:2 -/
def
  __anodized_fn_ensures_collatz.closure.Insts.CoreOpsFunctionFnOnceTupleSharedintBool.call_once
  (c : __anodized_fn_ensures_collatz.closure)
  (i : anodized_logic.arithmetic.int) :
  Result Bool
  := do
  let (b, _) ←
    __anodized_fn_ensures_collatz.closure.Insts.CoreOpsFunctionFnMutTupleSharedintBool.call_mut
      c i
  ok b

/-- Trait implementation: [e02::__anodized_fn_ensures_collatz::{impl core::ops::function::FnOnce<(&'_ anodized_logic::arithmetic::int,), bool> for e02::__anodized_fn_ensures_collatz::closure}]
    Source: 'examples/e02/src/lib.rs', lines 4:0-7:2 -/
@[reducible]
def
  __anodized_fn_ensures_collatz.closure.Insts.CoreOpsFunctionFnOnceTupleSharedintBool
  : core.ops.function.FnOnce __anodized_fn_ensures_collatz.closure
  anodized_logic.arithmetic.int Bool := {
  call_once :=
    __anodized_fn_ensures_collatz.closure.Insts.CoreOpsFunctionFnOnceTupleSharedintBool.call_once
}

/-- Trait implementation: [e02::__anodized_fn_ensures_collatz::{impl core::ops::function::FnMut<(&'_ anodized_logic::arithmetic::int,), bool> for e02::__anodized_fn_ensures_collatz::closure}]
    Source: 'examples/e02/src/lib.rs', lines 4:0-7:2 -/
@[reducible]
def
  __anodized_fn_ensures_collatz.closure.Insts.CoreOpsFunctionFnMutTupleSharedintBool
  : core.ops.function.FnMut __anodized_fn_ensures_collatz.closure
  anodized_logic.arithmetic.int Bool := {
  FnOnceInst :=
    __anodized_fn_ensures_collatz.closure.Insts.CoreOpsFunctionFnOnceTupleSharedintBool
  call_mut :=
    __anodized_fn_ensures_collatz.closure.Insts.CoreOpsFunctionFnMutTupleSharedintBool.call_mut
}

/-- Trait implementation: [e02::__anodized_fn_ensures_collatz::{impl core::ops::function::Fn<(&'_ anodized_logic::arithmetic::int,), bool> for e02::__anodized_fn_ensures_collatz::closure}]
    Source: 'examples/e02/src/lib.rs', lines 4:0-7:2 -/
@[reducible]
def
  __anodized_fn_ensures_collatz.closure.Insts.CoreOpsFunctionFnTupleSharedintBool
  : core.ops.function.Fn __anodized_fn_ensures_collatz.closure
  anodized_logic.arithmetic.int Bool := {
  FnMutInst :=
    __anodized_fn_ensures_collatz.closure.Insts.CoreOpsFunctionFnMutTupleSharedintBool
  call :=
    __anodized_fn_ensures_collatz.closure.Insts.CoreOpsFunctionFnTupleSharedintBool.call
}

/-- [e02::__anodized_fn_requires_collatz]:
    Source: 'examples/e02/src/lib.rs', lines 4:0-7:2 -/
def __anodized_fn_requires_collatz
  (n : anodized_logic.arithmetic.int) : Result Bool := do
  __anodized_fn_requires_collatz.closure.Insts.CoreOpsFunctionFnTupleBool.call
    n ()

/-- [e02::__anodized_fn_ensures_collatz]:
    Source: 'examples/e02/src/lib.rs', lines 4:0-7:2 -/
def __anodized_fn_ensures_collatz
  (n : anodized_logic.arithmetic.int)
  (__anodized_output : anodized_logic.arithmetic.int) :
  Result Bool
  := do
  __anodized_fn_ensures_collatz.closure.Insts.CoreOpsFunctionFnTupleSharedintBool.call
    () __anodized_output

/-- [e02::__anodized_fn_qualifiers_collatz]
    Source: 'examples/e02/src/lib.rs', lines 4:0-7:2 -/
@[global_simps, irreducible]
def __anodized_fn_qualifiers_collatz : Std.U32 := 0#u32

/-- [e02::f]:
    Source: 'examples/e02/src/lib.rs', lines 15:0-21:1 -/
def f
  (n : anodized_logic.arithmetic.int) :
  Result anodized_logic.arithmetic.int
  := do
  let i ← Shared0int.Insts.CoreOpsArithRemI32int.rem n 2#i32
  let b ← anodized_logic.arithmetic.int.Insts.CoreCmpPartialEqI32.eq i 0#i32
  if b
  then Shared0int.Insts.CoreOpsArithDivI32int.div n 2#i32
  else
    let i1 ← I32.Insts.CoreOpsArithMulShared0intint.mul 3#i32 n
    anodized_logic.arithmetic.int.Insts.CoreOpsArithAddI32int.add i1 1#i32

/-- [e02::collatz]: loop body 0:
    Source: 'examples/e02/src/lib.rs', lines 0:0-11:5
    Visibility: public -/
@[rust_loop_body]
def collatz_loop.body
  (n : anodized_logic.arithmetic.int) :
  Result (ControlFlow anodized_logic.arithmetic.int
    anodized_logic.arithmetic.int)
  := do
  let b ← anodized_logic.arithmetic.int.Insts.CoreCmpPartialOrdI32.gt n 1#i32
  if b
  then let n1 ← f n
       ok (cont n1)
  else ok (done n)

/-- [e02::collatz]: loop 0:
    Source: 'examples/e02/src/lib.rs', lines 0:0-11:5
    Visibility: public -/
@[rust_loop]
def collatz_loop
  (n : anodized_logic.arithmetic.int) :
  Result anodized_logic.arithmetic.int
  := do
  loop
    (fun n1 => collatz_loop.body n1)
    n

/-- [e02::collatz]:
    Source: 'examples/e02/src/lib.rs', lines 8:0-13:1
    Visibility: public -/
@[reducible]
def collatz
  (n : anodized_logic.arithmetic.int) :
  Result anodized_logic.arithmetic.int
  := do
  collatz_loop n

end e02
