-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [e02]: function definitions
import Aeneas
import examples.e02.translation.Types
import examples.e02.translation.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace e02

/-- [e02::__anodized_fn_requires_collatz::{impl core::ops::function::Fn<(), bool> for e02::__anodized_fn_requires_collatz::closure<'_0>}::call]:
    Source: 'examples/e02/src/lib.rs', lines 4:0-7:2 -/
def
  __anodized_fn_requires_collatz.closure.Insts.CoreOpsFunctionFnTupleBool.call
  (c : __anodized_fn_requires_collatz.closure) (_ : Unit) : Result Bool := do
  anodized_logic.arithmetic.int.Insts.CoreCmpPartialOrdI32.gt c 0#i32

/-- [e02::__anodized_fn_requires_collatz::{impl core::ops::function::FnMut<(), bool> for e02::__anodized_fn_requires_collatz::closure<'_0>}::call_mut]:
    Source: 'examples/e02/src/lib.rs', lines 4:0-7:2 -/
def
  __anodized_fn_requires_collatz.closure.Insts.CoreOpsFunctionFnMutTupleBool.call_mut
  (state : __anodized_fn_requires_collatz.closure) (_ : Unit) :
  Result (Bool × __anodized_fn_requires_collatz.closure)
  := do
  let b ←
    __anodized_fn_requires_collatz.closure.Insts.CoreOpsFunctionFnTupleBool.call
      state ()
  ok (b, state)

/-- [e02::__anodized_fn_requires_collatz::{impl core::ops::function::FnOnce<(), bool> for e02::__anodized_fn_requires_collatz::closure<'_0>}::call_once]:
    Source: 'examples/e02/src/lib.rs', lines 4:0-7:2 -/
def
  __anodized_fn_requires_collatz.closure.Insts.CoreOpsFunctionFnOnceTupleBool.call_once
  (c : __anodized_fn_requires_collatz.closure) (_ : Unit) : Result Bool := do
  let (b, _) ←
    __anodized_fn_requires_collatz.closure.Insts.CoreOpsFunctionFnMutTupleBool.call_mut
      c ()
  ok b

/-- Trait implementation: [e02::__anodized_fn_requires_collatz::{impl core::ops::function::FnOnce<(), bool> for e02::__anodized_fn_requires_collatz::closure<'_0>}]
    Source: 'examples/e02/src/lib.rs', lines 4:0-7:2 -/
@[reducible]
def __anodized_fn_requires_collatz.closure.Insts.CoreOpsFunctionFnOnceTupleBool
  : core.ops.function.FnOnce __anodized_fn_requires_collatz.closure Unit Bool
  := {
  call_once :=
    __anodized_fn_requires_collatz.closure.Insts.CoreOpsFunctionFnOnceTupleBool.call_once
}

/-- Trait implementation: [e02::__anodized_fn_requires_collatz::{impl core::ops::function::FnMut<(), bool> for e02::__anodized_fn_requires_collatz::closure<'_0>}]
    Source: 'examples/e02/src/lib.rs', lines 4:0-7:2 -/
@[reducible]
def __anodized_fn_requires_collatz.closure.Insts.CoreOpsFunctionFnMutTupleBool
  : core.ops.function.FnMut __anodized_fn_requires_collatz.closure Unit Bool
  := {
  FnOnceInst :=
    __anodized_fn_requires_collatz.closure.Insts.CoreOpsFunctionFnOnceTupleBool
  call_mut :=
    __anodized_fn_requires_collatz.closure.Insts.CoreOpsFunctionFnMutTupleBool.call_mut
}

/-- Trait implementation: [e02::__anodized_fn_requires_collatz::{impl core::ops::function::Fn<(), bool> for e02::__anodized_fn_requires_collatz::closure<'_0>}]
    Source: 'examples/e02/src/lib.rs', lines 4:0-7:2 -/
@[reducible]
def __anodized_fn_requires_collatz.closure.Insts.CoreOpsFunctionFnTupleBool :
  core.ops.function.Fn __anodized_fn_requires_collatz.closure Unit Bool := {
  FnMutInst :=
    __anodized_fn_requires_collatz.closure.Insts.CoreOpsFunctionFnMutTupleBool
  call :=
    __anodized_fn_requires_collatz.closure.Insts.CoreOpsFunctionFnTupleBool.call
}

/-- [e02::__anodized_fn_ensures_collatz::{impl core::ops::function::Fn<(&'_ anodized_logic::arithmetic::int,), bool> for e02::__anodized_fn_ensures_collatz::closure}::call]:
    Source: 'examples/e02/src/lib.rs', lines 4:0-7:2 -/
def
  __anodized_fn_ensures_collatz.closure.Insts.CoreOpsFunctionFnTupleSharedintBool.call
  (c : __anodized_fn_ensures_collatz.closure)
  (tupled_args : anodized_logic.arithmetic.int) :
  Result Bool
  := do
  anodized_logic.arithmetic.int.Insts.CoreCmpPartialEqI32.eq tupled_args 1#i32

/-- [e02::__anodized_fn_ensures_collatz::{impl core::ops::function::FnMut<(&'_ anodized_logic::arithmetic::int,), bool> for e02::__anodized_fn_ensures_collatz::closure}::call_mut]:
    Source: 'examples/e02/src/lib.rs', lines 4:0-7:2 -/
def
  __anodized_fn_ensures_collatz.closure.Insts.CoreOpsFunctionFnMutTupleSharedintBool.call_mut
  (state : __anodized_fn_ensures_collatz.closure)
  (args : anodized_logic.arithmetic.int) :
  Result (Bool × __anodized_fn_ensures_collatz.closure)
  := do
  let b ←
    __anodized_fn_ensures_collatz.closure.Insts.CoreOpsFunctionFnTupleSharedintBool.call
      state args
  ok (b, state)

/-- [e02::__anodized_fn_ensures_collatz::{impl core::ops::function::FnOnce<(&'_ anodized_logic::arithmetic::int,), bool> for e02::__anodized_fn_ensures_collatz::closure}::call_once]:
    Source: 'examples/e02/src/lib.rs', lines 4:0-7:2 -/
def
  __anodized_fn_ensures_collatz.closure.Insts.CoreOpsFunctionFnOnceTupleSharedintBool.call_once
  (c : __anodized_fn_ensures_collatz.closure)
  (i : anodized_logic.arithmetic.int) :
  Result Bool
  := do
  let (b, _) ←
    __anodized_fn_ensures_collatz.closure.Insts.CoreOpsFunctionFnMutTupleSharedintBool.call_mut
      c i
  ok b

/-- Trait implementation: [e02::__anodized_fn_ensures_collatz::{impl core::ops::function::FnOnce<(&'_ anodized_logic::arithmetic::int,), bool> for e02::__anodized_fn_ensures_collatz::closure}]
    Source: 'examples/e02/src/lib.rs', lines 4:0-7:2 -/
@[reducible]
def
  __anodized_fn_ensures_collatz.closure.Insts.CoreOpsFunctionFnOnceTupleSharedintBool
  : core.ops.function.FnOnce __anodized_fn_ensures_collatz.closure
  anodized_logic.arithmetic.int Bool := {
  call_once :=
    __anodized_fn_ensures_collatz.closure.Insts.CoreOpsFunctionFnOnceTupleSharedintBool.call_once
}

/-- Trait implementation: [e02::__anodized_fn_ensures_collatz::{impl core::ops::function::FnMut<(&'_ anodized_logic::arithmetic::int,), bool> for e02::__anodized_fn_ensures_collatz::closure}]
    Source: 'examples/e02/src/lib.rs', lines 4:0-7:2 -/
@[reducible]
def
  __anodized_fn_ensures_collatz.closure.Insts.CoreOpsFunctionFnMutTupleSharedintBool
  : core.ops.function.FnMut __anodized_fn_ensures_collatz.closure
  anodized_logic.arithmetic.int Bool := {
  FnOnceInst :=
    __anodized_fn_ensures_collatz.closure.Insts.CoreOpsFunctionFnOnceTupleSharedintBool
  call_mut :=
    __anodized_fn_ensures_collatz.closure.Insts.CoreOpsFunctionFnMutTupleSharedintBool.call_mut
}

/-- Trait implementation: [e02::__anodized_fn_ensures_collatz::{impl core::ops::function::Fn<(&'_ anodized_logic::arithmetic::int,), bool> for e02::__anodized_fn_ensures_collatz::closure}]
    Source: 'examples/e02/src/lib.rs', lines 4:0-7:2 -/
@[reducible]
def
  __anodized_fn_ensures_collatz.closure.Insts.CoreOpsFunctionFnTupleSharedintBool
  : core.ops.function.Fn __anodized_fn_ensures_collatz.closure
  anodized_logic.arithmetic.int Bool := {
  FnMutInst :=
    __anodized_fn_ensures_collatz.closure.Insts.CoreOpsFunctionFnMutTupleSharedintBool
  call :=
    __anodized_fn_ensures_collatz.closure.Insts.CoreOpsFunctionFnTupleSharedintBool.call
}

/-- [e02::__anodized_fn_requires_collatz]:
    Source: 'examples/e02/src/lib.rs', lines 4:0-7:2 -/
def __anodized_fn_requires_collatz
  (n : anodized_logic.arithmetic.int) : Result Bool := do
  __anodized_fn_requires_collatz.closure.Insts.CoreOpsFunctionFnTupleBool.call
    n ()

/-- [e02::__anodized_fn_ensures_collatz]:
    Source: 'examples/e02/src/lib.rs', lines 4:0-7:2 -/
def __anodized_fn_ensures_collatz
  (n : anodized_logic.arithmetic.int)
  (__anodized_output : anodized_logic.arithmetic.int) :
  Result Bool
  := do
  __anodized_fn_ensures_collatz.closure.Insts.CoreOpsFunctionFnTupleSharedintBool.call
    () __anodized_output

/-- [e02::__anodized_fn_qualifiers_collatz]
    Source: 'examples/e02/src/lib.rs', lines 4:0-7:2 -/
@[global_simps, irreducible]
def __anodized_fn_qualifiers_collatz : Std.U32 := 0#u32

/-- [e02::f]:
    Source: 'examples/e02/src/lib.rs', lines 15:0-21:1 -/
def f
  (n : anodized_logic.arithmetic.int) :
  Result anodized_logic.arithmetic.int
  := do
  let i ← Shared0int.Insts.CoreOpsArithRemI32int.rem n 2#i32
  let b ← anodized_logic.arithmetic.int.Insts.CoreCmpPartialEqI32.eq i 0#i32
  if b
  then Shared0int.Insts.CoreOpsArithDivI32int.div n 2#i32
  else
    let i1 ← I32.Insts.CoreOpsArithMulShared0intint.mul 3#i32 n
    anodized_logic.arithmetic.int.Insts.CoreOpsArithAddI32int.add i1 1#i32

/-- [e02::collatz]: loop body 0:
    Source: 'examples/e02/src/lib.rs', lines 0:0-11:5
    Visibility: public -/
@[rust_loop_body]
def collatz_loop.body
  (n : anodized_logic.arithmetic.int) :
  Result (ControlFlow anodized_logic.arithmetic.int
    anodized_logic.arithmetic.int)
  := do
  let b ← anodized_logic.arithmetic.int.Insts.CoreCmpPartialOrdI32.gt n 1#i32
  if b
  then let n1 ← f n
       ok (cont n1)
  else ok (done n)

/-- [e02::collatz]: loop 0:
    Source: 'examples/e02/src/lib.rs', lines 0:0-11:5
    Visibility: public -/
@[rust_loop]
def collatz_loop
  (n : anodized_logic.arithmetic.int) :
  Result anodized_logic.arithmetic.int
  := do
  loop
    (fun n1 => collatz_loop.body n1)
    n

/-- [e02::collatz]:
    Source: 'examples/e02/src/lib.rs', lines 8:0-13:1
    Visibility: public -/
@[reducible]
def collatz
  (n : anodized_logic.arithmetic.int) :
  Result anodized_logic.arithmetic.int
  := do
  collatz_loop n

/-- [e02::__anodized_fn_requires_decrement::{impl core::ops::function::Fn<(), bool> for e02::__anodized_fn_requires_decrement::closure<'_0>}::call]:
    Source: 'examples/e02/src/lib.rs', lines 28:0-31:2 -/
def
  __anodized_fn_requires_decrement.closure.Insts.CoreOpsFunctionFnTupleBool.call
  (c : __anodized_fn_requires_decrement.closure) (_ : Unit) : Result Bool := do
  ok (c > 0#u8)

/-- [e02::__anodized_fn_requires_decrement::{impl core::ops::function::FnMut<(), bool> for e02::__anodized_fn_requires_decrement::closure<'_0>}::call_mut]:
    Source: 'examples/e02/src/lib.rs', lines 28:0-31:2 -/
def
  __anodized_fn_requires_decrement.closure.Insts.CoreOpsFunctionFnMutTupleBool.call_mut
  (state : __anodized_fn_requires_decrement.closure) (_ : Unit) :
  Result (Bool × __anodized_fn_requires_decrement.closure)
  := do
  let b ←
    __anodized_fn_requires_decrement.closure.Insts.CoreOpsFunctionFnTupleBool.call
      state ()
  ok (b, state)

/-- [e02::__anodized_fn_requires_decrement::{impl core::ops::function::FnOnce<(), bool> for e02::__anodized_fn_requires_decrement::closure<'_0>}::call_once]:
    Source: 'examples/e02/src/lib.rs', lines 28:0-31:2 -/
def
  __anodized_fn_requires_decrement.closure.Insts.CoreOpsFunctionFnOnceTupleBool.call_once
  (c : __anodized_fn_requires_decrement.closure) (_ : Unit) : Result Bool := do
  let (b, _) ←
    __anodized_fn_requires_decrement.closure.Insts.CoreOpsFunctionFnMutTupleBool.call_mut
      c ()
  ok b

/-- Trait implementation: [e02::__anodized_fn_requires_decrement::{impl core::ops::function::FnOnce<(), bool> for e02::__anodized_fn_requires_decrement::closure<'_0>}]
    Source: 'examples/e02/src/lib.rs', lines 28:0-31:2 -/
@[reducible]
def
  __anodized_fn_requires_decrement.closure.Insts.CoreOpsFunctionFnOnceTupleBool
  : core.ops.function.FnOnce __anodized_fn_requires_decrement.closure Unit Bool
  := {
  call_once :=
    __anodized_fn_requires_decrement.closure.Insts.CoreOpsFunctionFnOnceTupleBool.call_once
}

/-- Trait implementation: [e02::__anodized_fn_requires_decrement::{impl core::ops::function::FnMut<(), bool> for e02::__anodized_fn_requires_decrement::closure<'_0>}]
    Source: 'examples/e02/src/lib.rs', lines 28:0-31:2 -/
@[reducible]
def
  __anodized_fn_requires_decrement.closure.Insts.CoreOpsFunctionFnMutTupleBool
  : core.ops.function.FnMut __anodized_fn_requires_decrement.closure Unit Bool
  := {
  FnOnceInst :=
    __anodized_fn_requires_decrement.closure.Insts.CoreOpsFunctionFnOnceTupleBool
  call_mut :=
    __anodized_fn_requires_decrement.closure.Insts.CoreOpsFunctionFnMutTupleBool.call_mut
}

/-- Trait implementation: [e02::__anodized_fn_requires_decrement::{impl core::ops::function::Fn<(), bool> for e02::__anodized_fn_requires_decrement::closure<'_0>}]
    Source: 'examples/e02/src/lib.rs', lines 28:0-31:2 -/
@[reducible]
def __anodized_fn_requires_decrement.closure.Insts.CoreOpsFunctionFnTupleBool :
  core.ops.function.Fn __anodized_fn_requires_decrement.closure Unit Bool := {
  FnMutInst :=
    __anodized_fn_requires_decrement.closure.Insts.CoreOpsFunctionFnMutTupleBool
  call :=
    __anodized_fn_requires_decrement.closure.Insts.CoreOpsFunctionFnTupleBool.call
}

/-- [e02::__anodized_fn_ensures_decrement::{impl core::ops::function::Fn<(&'_ u8,), bool> for e02::__anodized_fn_ensures_decrement::closure<'_0>}::call]:
    Source: 'examples/e02/src/lib.rs', lines 28:0-31:2 -/
def
  __anodized_fn_ensures_decrement.closure.Insts.CoreOpsFunctionFnTupleSharedU8Bool.call
  (c : __anodized_fn_ensures_decrement.closure) (tupled_args : Std.U8) :
  Result Bool
  := do
  let i ←
    anodized_logic.arithmetic.int.Insts.CoreConvertFromU8.from tupled_args
  let i1 ← anodized_logic.arithmetic.int.Insts.CoreConvertFromU8.from c
  let i2 ← anodized_logic.arithmetic.int.Insts.CoreConvertFromU8.from 1#u8
  let i3 ←
    anodized_logic.arithmetic.int.Insts.CoreOpsArithSubintint.sub i1 i2
  anodized_logic.arithmetic.int.Insts.CoreCmpPartialEqint.eq i i3

/-- [e02::__anodized_fn_ensures_decrement::{impl core::ops::function::FnMut<(&'_ u8,), bool> for e02::__anodized_fn_ensures_decrement::closure<'_0>}::call_mut]:
    Source: 'examples/e02/src/lib.rs', lines 28:0-31:2 -/
def
  __anodized_fn_ensures_decrement.closure.Insts.CoreOpsFunctionFnMutTupleSharedU8Bool.call_mut
  (state : __anodized_fn_ensures_decrement.closure) (args : Std.U8) :
  Result (Bool × __anodized_fn_ensures_decrement.closure)
  := do
  let b ←
    __anodized_fn_ensures_decrement.closure.Insts.CoreOpsFunctionFnTupleSharedU8Bool.call
      state args
  ok (b, state)

/-- [e02::__anodized_fn_ensures_decrement::{impl core::ops::function::FnOnce<(&'_ u8,), bool> for e02::__anodized_fn_ensures_decrement::closure<'_0>}::call_once]:
    Source: 'examples/e02/src/lib.rs', lines 28:0-31:2 -/
def
  __anodized_fn_ensures_decrement.closure.Insts.CoreOpsFunctionFnOnceTupleSharedU8Bool.call_once
  (c : __anodized_fn_ensures_decrement.closure) (i : Std.U8) :
  Result Bool
  := do
  let (b, _) ←
    __anodized_fn_ensures_decrement.closure.Insts.CoreOpsFunctionFnMutTupleSharedU8Bool.call_mut
      c i
  ok b

/-- Trait implementation: [e02::__anodized_fn_ensures_decrement::{impl core::ops::function::FnOnce<(&'_ u8,), bool> for e02::__anodized_fn_ensures_decrement::closure<'_0>}]
    Source: 'examples/e02/src/lib.rs', lines 28:0-31:2 -/
@[reducible]
def
  __anodized_fn_ensures_decrement.closure.Insts.CoreOpsFunctionFnOnceTupleSharedU8Bool
  : core.ops.function.FnOnce __anodized_fn_ensures_decrement.closure Std.U8
  Bool := {
  call_once :=
    __anodized_fn_ensures_decrement.closure.Insts.CoreOpsFunctionFnOnceTupleSharedU8Bool.call_once
}

/-- Trait implementation: [e02::__anodized_fn_ensures_decrement::{impl core::ops::function::FnMut<(&'_ u8,), bool> for e02::__anodized_fn_ensures_decrement::closure<'_0>}]
    Source: 'examples/e02/src/lib.rs', lines 28:0-31:2 -/
@[reducible]
def
  __anodized_fn_ensures_decrement.closure.Insts.CoreOpsFunctionFnMutTupleSharedU8Bool
  : core.ops.function.FnMut __anodized_fn_ensures_decrement.closure Std.U8 Bool
  := {
  FnOnceInst :=
    __anodized_fn_ensures_decrement.closure.Insts.CoreOpsFunctionFnOnceTupleSharedU8Bool
  call_mut :=
    __anodized_fn_ensures_decrement.closure.Insts.CoreOpsFunctionFnMutTupleSharedU8Bool.call_mut
}

/-- Trait implementation: [e02::__anodized_fn_ensures_decrement::{impl core::ops::function::Fn<(&'_ u8,), bool> for e02::__anodized_fn_ensures_decrement::closure<'_0>}]
    Source: 'examples/e02/src/lib.rs', lines 28:0-31:2 -/
@[reducible]
def
  __anodized_fn_ensures_decrement.closure.Insts.CoreOpsFunctionFnTupleSharedU8Bool
  : core.ops.function.Fn __anodized_fn_ensures_decrement.closure Std.U8 Bool
  := {
  FnMutInst :=
    __anodized_fn_ensures_decrement.closure.Insts.CoreOpsFunctionFnMutTupleSharedU8Bool
  call :=
    __anodized_fn_ensures_decrement.closure.Insts.CoreOpsFunctionFnTupleSharedU8Bool.call
}

/-- [e02::__anodized_fn_requires_decrement]:
    Source: 'examples/e02/src/lib.rs', lines 28:0-31:2 -/
def __anodized_fn_requires_decrement (x : Std.U8) : Result Bool := do
  __anodized_fn_requires_decrement.closure.Insts.CoreOpsFunctionFnTupleBool.call
    x ()

/-- [e02::__anodized_fn_ensures_decrement]:
    Source: 'examples/e02/src/lib.rs', lines 28:0-31:2 -/
def __anodized_fn_ensures_decrement
  (x : Std.U8) (__anodized_output : Std.U8) : Result Bool := do
  __anodized_fn_ensures_decrement.closure.Insts.CoreOpsFunctionFnTupleSharedU8Bool.call
    x __anodized_output

/-- [e02::__anodized_fn_qualifiers_decrement]
    Source: 'examples/e02/src/lib.rs', lines 28:0-31:2 -/
@[global_simps, irreducible]
def __anodized_fn_qualifiers_decrement : Std.U32 := 0#u32

/-- [e02::decrement]:
    Source: 'examples/e02/src/lib.rs', lines 32:0-34:1
    Visibility: public -/
def decrement (x : Std.U8) : Result Std.U8 := do
  x - 1#u8

/-- [e02::__anodized_fn_requires_add::{impl core::ops::function::Fn<(), bool> for e02::__anodized_fn_requires_add::closure<'_0, '_1>}::call]:
    Source: 'examples/e02/src/lib.rs', lines 36:0-39:2 -/
def __anodized_fn_requires_add.closure.Insts.CoreOpsFunctionFnTupleBool.call
  (c : __anodized_fn_requires_add.closure) (_ : Unit) : Result Bool := do
  let (i, i1) := c
  let i2 ← anodized_logic.arithmetic.int.Insts.CoreConvertFromU8.from i
  let i3 ← anodized_logic.arithmetic.int.Insts.CoreConvertFromU8.from i1
  let i4 ←
    anodized_logic.arithmetic.int.Insts.CoreOpsArithAddintint.add i2 i3
  let i5 ← anodized_logic.arithmetic.int.Insts.CoreConvertFromU8.from 255#u8
  anodized_logic.arithmetic.int.Insts.CoreCmpPartialOrdint.le i4 i5

/-- [e02::__anodized_fn_requires_add::{impl core::ops::function::FnMut<(), bool> for e02::__anodized_fn_requires_add::closure<'_0, '_1>}::call_mut]:
    Source: 'examples/e02/src/lib.rs', lines 36:0-39:2 -/
def
  __anodized_fn_requires_add.closure.Insts.CoreOpsFunctionFnMutTupleBool.call_mut
  (state : __anodized_fn_requires_add.closure) (_ : Unit) :
  Result (Bool × __anodized_fn_requires_add.closure)
  := do
  let b ←
    __anodized_fn_requires_add.closure.Insts.CoreOpsFunctionFnTupleBool.call
      state ()
  ok (b, state)

/-- [e02::__anodized_fn_requires_add::{impl core::ops::function::FnOnce<(), bool> for e02::__anodized_fn_requires_add::closure<'_0, '_1>}::call_once]:
    Source: 'examples/e02/src/lib.rs', lines 36:0-39:2 -/
def
  __anodized_fn_requires_add.closure.Insts.CoreOpsFunctionFnOnceTupleBool.call_once
  (c : __anodized_fn_requires_add.closure) (_ : Unit) : Result Bool := do
  let (b, _) ←
    __anodized_fn_requires_add.closure.Insts.CoreOpsFunctionFnMutTupleBool.call_mut
      c ()
  ok b

/-- Trait implementation: [e02::__anodized_fn_requires_add::{impl core::ops::function::FnOnce<(), bool> for e02::__anodized_fn_requires_add::closure<'_0, '_1>}]
    Source: 'examples/e02/src/lib.rs', lines 36:0-39:2 -/
@[reducible]
def __anodized_fn_requires_add.closure.Insts.CoreOpsFunctionFnOnceTupleBool :
  core.ops.function.FnOnce __anodized_fn_requires_add.closure Unit Bool := {
  call_once :=
    __anodized_fn_requires_add.closure.Insts.CoreOpsFunctionFnOnceTupleBool.call_once
}

/-- Trait implementation: [e02::__anodized_fn_requires_add::{impl core::ops::function::FnMut<(), bool> for e02::__anodized_fn_requires_add::closure<'_0, '_1>}]
    Source: 'examples/e02/src/lib.rs', lines 36:0-39:2 -/
@[reducible]
def __anodized_fn_requires_add.closure.Insts.CoreOpsFunctionFnMutTupleBool :
  core.ops.function.FnMut __anodized_fn_requires_add.closure Unit Bool := {
  FnOnceInst :=
    __anodized_fn_requires_add.closure.Insts.CoreOpsFunctionFnOnceTupleBool
  call_mut :=
    __anodized_fn_requires_add.closure.Insts.CoreOpsFunctionFnMutTupleBool.call_mut
}

/-- Trait implementation: [e02::__anodized_fn_requires_add::{impl core::ops::function::Fn<(), bool> for e02::__anodized_fn_requires_add::closure<'_0, '_1>}]
    Source: 'examples/e02/src/lib.rs', lines 36:0-39:2 -/
@[reducible]
def __anodized_fn_requires_add.closure.Insts.CoreOpsFunctionFnTupleBool :
  core.ops.function.Fn __anodized_fn_requires_add.closure Unit Bool := {
  FnMutInst :=
    __anodized_fn_requires_add.closure.Insts.CoreOpsFunctionFnMutTupleBool
  call :=
    __anodized_fn_requires_add.closure.Insts.CoreOpsFunctionFnTupleBool.call
}

/-- [e02::__anodized_fn_ensures_add::{impl core::ops::function::Fn<(&'_ u8,), bool> for e02::__anodized_fn_ensures_add::closure<'_0, '_1>}::call]:
    Source: 'examples/e02/src/lib.rs', lines 36:0-39:2 -/
def
  __anodized_fn_ensures_add.closure.Insts.CoreOpsFunctionFnTupleSharedU8Bool.call
  (c : __anodized_fn_ensures_add.closure) (tupled_args : Std.U8) :
  Result Bool
  := do
  let (i, i1) := c
  let i2 ←
    anodized_logic.arithmetic.int.Insts.CoreConvertFromU8.from tupled_args
  let i3 ← anodized_logic.arithmetic.int.Insts.CoreConvertFromU8.from i
  let i4 ← anodized_logic.arithmetic.int.Insts.CoreConvertFromU8.from i1
  let i5 ←
    anodized_logic.arithmetic.int.Insts.CoreOpsArithAddintint.add i3 i4
  anodized_logic.arithmetic.int.Insts.CoreCmpPartialEqint.eq i2 i5

/-- [e02::__anodized_fn_ensures_add::{impl core::ops::function::FnMut<(&'_ u8,), bool> for e02::__anodized_fn_ensures_add::closure<'_0, '_1>}::call_mut]:
    Source: 'examples/e02/src/lib.rs', lines 36:0-39:2 -/
def
  __anodized_fn_ensures_add.closure.Insts.CoreOpsFunctionFnMutTupleSharedU8Bool.call_mut
  (state : __anodized_fn_ensures_add.closure) (args : Std.U8) :
  Result (Bool × __anodized_fn_ensures_add.closure)
  := do
  let b ←
    __anodized_fn_ensures_add.closure.Insts.CoreOpsFunctionFnTupleSharedU8Bool.call
      state args
  ok (b, state)

/-- [e02::__anodized_fn_ensures_add::{impl core::ops::function::FnOnce<(&'_ u8,), bool> for e02::__anodized_fn_ensures_add::closure<'_0, '_1>}::call_once]:
    Source: 'examples/e02/src/lib.rs', lines 36:0-39:2 -/
def
  __anodized_fn_ensures_add.closure.Insts.CoreOpsFunctionFnOnceTupleSharedU8Bool.call_once
  (c : __anodized_fn_ensures_add.closure) (i : Std.U8) : Result Bool := do
  let (b, _) ←
    __anodized_fn_ensures_add.closure.Insts.CoreOpsFunctionFnMutTupleSharedU8Bool.call_mut
      c i
  ok b

/-- Trait implementation: [e02::__anodized_fn_ensures_add::{impl core::ops::function::FnOnce<(&'_ u8,), bool> for e02::__anodized_fn_ensures_add::closure<'_0, '_1>}]
    Source: 'examples/e02/src/lib.rs', lines 36:0-39:2 -/
@[reducible]
def
  __anodized_fn_ensures_add.closure.Insts.CoreOpsFunctionFnOnceTupleSharedU8Bool
  : core.ops.function.FnOnce __anodized_fn_ensures_add.closure Std.U8 Bool := {
  call_once :=
    __anodized_fn_ensures_add.closure.Insts.CoreOpsFunctionFnOnceTupleSharedU8Bool.call_once
}

/-- Trait implementation: [e02::__anodized_fn_ensures_add::{impl core::ops::function::FnMut<(&'_ u8,), bool> for e02::__anodized_fn_ensures_add::closure<'_0, '_1>}]
    Source: 'examples/e02/src/lib.rs', lines 36:0-39:2 -/
@[reducible]
def
  __anodized_fn_ensures_add.closure.Insts.CoreOpsFunctionFnMutTupleSharedU8Bool
  : core.ops.function.FnMut __anodized_fn_ensures_add.closure Std.U8 Bool := {
  FnOnceInst :=
    __anodized_fn_ensures_add.closure.Insts.CoreOpsFunctionFnOnceTupleSharedU8Bool
  call_mut :=
    __anodized_fn_ensures_add.closure.Insts.CoreOpsFunctionFnMutTupleSharedU8Bool.call_mut
}

/-- Trait implementation: [e02::__anodized_fn_ensures_add::{impl core::ops::function::Fn<(&'_ u8,), bool> for e02::__anodized_fn_ensures_add::closure<'_0, '_1>}]
    Source: 'examples/e02/src/lib.rs', lines 36:0-39:2 -/
@[reducible]
def __anodized_fn_ensures_add.closure.Insts.CoreOpsFunctionFnTupleSharedU8Bool
  : core.ops.function.Fn __anodized_fn_ensures_add.closure Std.U8 Bool := {
  FnMutInst :=
    __anodized_fn_ensures_add.closure.Insts.CoreOpsFunctionFnMutTupleSharedU8Bool
  call :=
    __anodized_fn_ensures_add.closure.Insts.CoreOpsFunctionFnTupleSharedU8Bool.call
}

/-- [e02::__anodized_fn_requires_add]:
    Source: 'examples/e02/src/lib.rs', lines 36:0-39:2 -/
def __anodized_fn_requires_add (x : Std.U8) (y : Std.U8) : Result Bool := do
  __anodized_fn_requires_add.closure.Insts.CoreOpsFunctionFnTupleBool.call (x,
    y) ()

/-- [e02::__anodized_fn_ensures_add]:
    Source: 'examples/e02/src/lib.rs', lines 36:0-39:2 -/
def __anodized_fn_ensures_add
  (x : Std.U8) (y : Std.U8) (__anodized_output : Std.U8) : Result Bool := do
  __anodized_fn_ensures_add.closure.Insts.CoreOpsFunctionFnTupleSharedU8Bool.call
    (x, y) __anodized_output

/-- [e02::__anodized_fn_qualifiers_add]
    Source: 'examples/e02/src/lib.rs', lines 36:0-39:2 -/
@[global_simps, irreducible]
def __anodized_fn_qualifiers_add : Std.U32 := 0#u32

/-- [e02::add]:
    Source: 'examples/e02/src/lib.rs', lines 40:0-42:1
    Visibility: public -/
def add (x : Std.U8) (y : Std.U8) : Result Std.U8 := do
  x + y

/-- [e02::__anodized_fn_requires_sub::{impl core::ops::function::Fn<(), bool> for e02::__anodized_fn_requires_sub::closure<'_0, '_1>}::call]:
    Source: 'examples/e02/src/lib.rs', lines 44:0-47:2 -/
def __anodized_fn_requires_sub.closure.Insts.CoreOpsFunctionFnTupleBool.call
  (c : __anodized_fn_requires_sub.closure) (_ : Unit) : Result Bool := do
  let (i, i1) := c
  let i2 ← anodized_logic.arithmetic.int.Insts.CoreConvertFromU8.from i
  let i3 ← anodized_logic.arithmetic.int.Insts.CoreConvertFromU8.from i1
  anodized_logic.arithmetic.int.Insts.CoreCmpPartialOrdint.le i2 i3

/-- [e02::__anodized_fn_requires_sub::{impl core::ops::function::FnMut<(), bool> for e02::__anodized_fn_requires_sub::closure<'_0, '_1>}::call_mut]:
    Source: 'examples/e02/src/lib.rs', lines 44:0-47:2 -/
def
  __anodized_fn_requires_sub.closure.Insts.CoreOpsFunctionFnMutTupleBool.call_mut
  (state : __anodized_fn_requires_sub.closure) (_ : Unit) :
  Result (Bool × __anodized_fn_requires_sub.closure)
  := do
  let b ←
    __anodized_fn_requires_sub.closure.Insts.CoreOpsFunctionFnTupleBool.call
      state ()
  ok (b, state)

/-- [e02::__anodized_fn_requires_sub::{impl core::ops::function::FnOnce<(), bool> for e02::__anodized_fn_requires_sub::closure<'_0, '_1>}::call_once]:
    Source: 'examples/e02/src/lib.rs', lines 44:0-47:2 -/
def
  __anodized_fn_requires_sub.closure.Insts.CoreOpsFunctionFnOnceTupleBool.call_once
  (c : __anodized_fn_requires_sub.closure) (_ : Unit) : Result Bool := do
  let (b, _) ←
    __anodized_fn_requires_sub.closure.Insts.CoreOpsFunctionFnMutTupleBool.call_mut
      c ()
  ok b

/-- Trait implementation: [e02::__anodized_fn_requires_sub::{impl core::ops::function::FnOnce<(), bool> for e02::__anodized_fn_requires_sub::closure<'_0, '_1>}]
    Source: 'examples/e02/src/lib.rs', lines 44:0-47:2 -/
@[reducible]
def __anodized_fn_requires_sub.closure.Insts.CoreOpsFunctionFnOnceTupleBool :
  core.ops.function.FnOnce __anodized_fn_requires_sub.closure Unit Bool := {
  call_once :=
    __anodized_fn_requires_sub.closure.Insts.CoreOpsFunctionFnOnceTupleBool.call_once
}

/-- Trait implementation: [e02::__anodized_fn_requires_sub::{impl core::ops::function::FnMut<(), bool> for e02::__anodized_fn_requires_sub::closure<'_0, '_1>}]
    Source: 'examples/e02/src/lib.rs', lines 44:0-47:2 -/
@[reducible]
def __anodized_fn_requires_sub.closure.Insts.CoreOpsFunctionFnMutTupleBool :
  core.ops.function.FnMut __anodized_fn_requires_sub.closure Unit Bool := {
  FnOnceInst :=
    __anodized_fn_requires_sub.closure.Insts.CoreOpsFunctionFnOnceTupleBool
  call_mut :=
    __anodized_fn_requires_sub.closure.Insts.CoreOpsFunctionFnMutTupleBool.call_mut
}

/-- Trait implementation: [e02::__anodized_fn_requires_sub::{impl core::ops::function::Fn<(), bool> for e02::__anodized_fn_requires_sub::closure<'_0, '_1>}]
    Source: 'examples/e02/src/lib.rs', lines 44:0-47:2 -/
@[reducible]
def __anodized_fn_requires_sub.closure.Insts.CoreOpsFunctionFnTupleBool :
  core.ops.function.Fn __anodized_fn_requires_sub.closure Unit Bool := {
  FnMutInst :=
    __anodized_fn_requires_sub.closure.Insts.CoreOpsFunctionFnMutTupleBool
  call :=
    __anodized_fn_requires_sub.closure.Insts.CoreOpsFunctionFnTupleBool.call
}

/-- [e02::__anodized_fn_ensures_sub::{impl core::ops::function::Fn<(&'_ u8,), bool> for e02::__anodized_fn_ensures_sub::closure<'_0, '_1>}::call]:
    Source: 'examples/e02/src/lib.rs', lines 44:0-47:2 -/
def
  __anodized_fn_ensures_sub.closure.Insts.CoreOpsFunctionFnTupleSharedU8Bool.call
  (c : __anodized_fn_ensures_sub.closure) (tupled_args : Std.U8) :
  Result Bool
  := do
  let (i, i1) := c
  let i2 ←
    anodized_logic.arithmetic.int.Insts.CoreConvertFromU8.from tupled_args
  let i3 ← anodized_logic.arithmetic.int.Insts.CoreConvertFromU8.from i
  let i4 ← anodized_logic.arithmetic.int.Insts.CoreConvertFromU8.from i1
  let i5 ←
    anodized_logic.arithmetic.int.Insts.CoreOpsArithSubintint.sub i3 i4
  anodized_logic.arithmetic.int.Insts.CoreCmpPartialEqint.eq i2 i5

/-- [e02::__anodized_fn_ensures_sub::{impl core::ops::function::FnMut<(&'_ u8,), bool> for e02::__anodized_fn_ensures_sub::closure<'_0, '_1>}::call_mut]:
    Source: 'examples/e02/src/lib.rs', lines 44:0-47:2 -/
def
  __anodized_fn_ensures_sub.closure.Insts.CoreOpsFunctionFnMutTupleSharedU8Bool.call_mut
  (state : __anodized_fn_ensures_sub.closure) (args : Std.U8) :
  Result (Bool × __anodized_fn_ensures_sub.closure)
  := do
  let b ←
    __anodized_fn_ensures_sub.closure.Insts.CoreOpsFunctionFnTupleSharedU8Bool.call
      state args
  ok (b, state)

/-- [e02::__anodized_fn_ensures_sub::{impl core::ops::function::FnOnce<(&'_ u8,), bool> for e02::__anodized_fn_ensures_sub::closure<'_0, '_1>}::call_once]:
    Source: 'examples/e02/src/lib.rs', lines 44:0-47:2 -/
def
  __anodized_fn_ensures_sub.closure.Insts.CoreOpsFunctionFnOnceTupleSharedU8Bool.call_once
  (c : __anodized_fn_ensures_sub.closure) (i : Std.U8) : Result Bool := do
  let (b, _) ←
    __anodized_fn_ensures_sub.closure.Insts.CoreOpsFunctionFnMutTupleSharedU8Bool.call_mut
      c i
  ok b

/-- Trait implementation: [e02::__anodized_fn_ensures_sub::{impl core::ops::function::FnOnce<(&'_ u8,), bool> for e02::__anodized_fn_ensures_sub::closure<'_0, '_1>}]
    Source: 'examples/e02/src/lib.rs', lines 44:0-47:2 -/
@[reducible]
def
  __anodized_fn_ensures_sub.closure.Insts.CoreOpsFunctionFnOnceTupleSharedU8Bool
  : core.ops.function.FnOnce __anodized_fn_ensures_sub.closure Std.U8 Bool := {
  call_once :=
    __anodized_fn_ensures_sub.closure.Insts.CoreOpsFunctionFnOnceTupleSharedU8Bool.call_once
}

/-- Trait implementation: [e02::__anodized_fn_ensures_sub::{impl core::ops::function::FnMut<(&'_ u8,), bool> for e02::__anodized_fn_ensures_sub::closure<'_0, '_1>}]
    Source: 'examples/e02/src/lib.rs', lines 44:0-47:2 -/
@[reducible]
def
  __anodized_fn_ensures_sub.closure.Insts.CoreOpsFunctionFnMutTupleSharedU8Bool
  : core.ops.function.FnMut __anodized_fn_ensures_sub.closure Std.U8 Bool := {
  FnOnceInst :=
    __anodized_fn_ensures_sub.closure.Insts.CoreOpsFunctionFnOnceTupleSharedU8Bool
  call_mut :=
    __anodized_fn_ensures_sub.closure.Insts.CoreOpsFunctionFnMutTupleSharedU8Bool.call_mut
}

/-- Trait implementation: [e02::__anodized_fn_ensures_sub::{impl core::ops::function::Fn<(&'_ u8,), bool> for e02::__anodized_fn_ensures_sub::closure<'_0, '_1>}]
    Source: 'examples/e02/src/lib.rs', lines 44:0-47:2 -/
@[reducible]
def __anodized_fn_ensures_sub.closure.Insts.CoreOpsFunctionFnTupleSharedU8Bool
  : core.ops.function.Fn __anodized_fn_ensures_sub.closure Std.U8 Bool := {
  FnMutInst :=
    __anodized_fn_ensures_sub.closure.Insts.CoreOpsFunctionFnMutTupleSharedU8Bool
  call :=
    __anodized_fn_ensures_sub.closure.Insts.CoreOpsFunctionFnTupleSharedU8Bool.call
}

/-- [e02::__anodized_fn_requires_sub]:
    Source: 'examples/e02/src/lib.rs', lines 44:0-47:2 -/
def __anodized_fn_requires_sub (x : Std.U8) (y : Std.U8) : Result Bool := do
  __anodized_fn_requires_sub.closure.Insts.CoreOpsFunctionFnTupleBool.call (y,
    x) ()

/-- [e02::__anodized_fn_ensures_sub]:
    Source: 'examples/e02/src/lib.rs', lines 44:0-47:2 -/
def __anodized_fn_ensures_sub
  (x : Std.U8) (y : Std.U8) (__anodized_output : Std.U8) : Result Bool := do
  __anodized_fn_ensures_sub.closure.Insts.CoreOpsFunctionFnTupleSharedU8Bool.call
    (x, y) __anodized_output

/-- [e02::__anodized_fn_qualifiers_sub]
    Source: 'examples/e02/src/lib.rs', lines 44:0-47:2 -/
@[global_simps, irreducible]
def __anodized_fn_qualifiers_sub : Std.U32 := 0#u32

/-- [e02::sub]:
    Source: 'examples/e02/src/lib.rs', lines 48:0-50:1
    Visibility: public -/
def sub (x : Std.U8) (y : Std.U8) : Result Std.U8 := do
  x - y

end e02
