-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [e02]: external types.
-- This is a template file: rename it to "TypesExternal.lean" and fill the holes.
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/-- [anodized_logic::arithmetic::int]
    Source: '/cargo/git/checkouts/anodized-c4166da61bc74ac3/f7e8e56/crates/anodized-logic/src/arithmetic.rs', lines 6:0-6:14
    Name pattern: [anodized_logic::arithmetic::int]
    Visibility: public -/
@[rust_type "anodized_logic::arithmetic::int"]
axiom anodized_logic.arithmetic.int : Type

