-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [e02]: type definitions
import Aeneas
import examples.e02.translation.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace e02

/-- [e02::__anodized_fn_requires_collatz::closure]
    Source: 'examples/e02/src/lib.rs', lines 4:0-7:2 -/
@[reducible]
def __anodized_fn_requires_collatz.closure := anodized_logic.arithmetic.int

/-- [e02::__anodized_fn_ensures_collatz::closure]
    Source: 'examples/e02/src/lib.rs', lines 4:0-7:2 -/
@[reducible]
def __anodized_fn_ensures_collatz.closure := Unit

/-- [e02::__anodized_fn_requires_decrement::closure]
    Source: 'examples/e02/src/lib.rs', lines 24:0-27:2 -/
@[reducible]
def __anodized_fn_requires_decrement.closure := Std.U8

/-- [e02::__anodized_fn_ensures_decrement::closure]
    Source: 'examples/e02/src/lib.rs', lines 24:0-27:2 -/
@[reducible]
def __anodized_fn_ensures_decrement.closure := Std.U8

/-- [e02::__anodized_fn_requires_add::closure]
    Source: 'examples/e02/src/lib.rs', lines 32:0-36:2 -/
def __anodized_fn_requires_add.closure := Std.U8 × Std.U8

/-- [e02::__anodized_fn_requires_add::closure#1]
    Source: 'examples/e02/src/lib.rs', lines 32:0-36:2 -/
@[reducible]
def __anodized_fn_requires_add.closure_1 := Std.U8

/-- [e02::__anodized_fn_ensures_add::closure]
    Source: 'examples/e02/src/lib.rs', lines 32:0-36:2 -/
def __anodized_fn_ensures_add.closure := Std.U8 × Std.U8

/-- [e02::__anodized_fn_requires_sub::closure]
    Source: 'examples/e02/src/lib.rs', lines 41:0-44:2 -/
def __anodized_fn_requires_sub.closure := Std.U8 × Std.U8

/-- [e02::__anodized_fn_ensures_sub::closure]
    Source: 'examples/e02/src/lib.rs', lines 41:0-44:2 -/
def __anodized_fn_ensures_sub.closure := Std.U8 × Std.U8

end e02
