-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [e02]: type definitions
import Aeneas
import examples.e02.translation.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace e02

/-- [e02::__anodized_fn_requires_collatz::closure]
    Source: 'examples/e02/src/lib.rs', lines 4:0-7:2 -/
@[reducible]
def __anodized_fn_requires_collatz.closure := anodized_logic.arithmetic.int

/-- [e02::__anodized_fn_ensures_collatz::closure]
    Source: 'examples/e02/src/lib.rs', lines 4:0-7:2 -/
@[reducible]
def __anodized_fn_ensures_collatz.closure := Unit

end e02
