name = "AeneasIntegration"
defaultTargets = ["examples"]

[leanOptions]
linter.style.nameCheck = false

# `rev` must be the same release tag pinned in aeneas-config.yml
[[require]]
name = "aeneas"
git = "https://github.com/AeneasVerif/aeneas.git"
subDir = "backends/lean"
rev = "nightly-2026.08.31-379890b"

[[lean_lib]]
name = "examples"

[[lean_lib]]
name = "Proofs"
