-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [e01]: function definitions
import Aeneas
import examples.e01.translation.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace e01

/-- [e01::__anodized_fn_requires_f1::{impl core::ops::function::Fn<(), bool> for e01::__anodized_fn_requires_f1::closure<'_0>}::call]:
    Source: 'examples/e01/src/lib.rs', lines 8:0-8:24 -/
def __anodized_fn_requires_f1.closure.Insts.CoreOpsFunctionFnTupleBool.call
  (c : __anodized_fn_requires_f1.closure) (_ : Unit) : Result Bool := do
  ok (c > 0#u8)

/-- [e01::__anodized_fn_requires_f1::{impl core::ops::function::FnMut<(), bool> for e01::__anodized_fn_requires_f1::closure<'_0>}::call_mut]:
    Source: 'examples/e01/src/lib.rs', lines 8:0-8:24 -/
def
  __anodized_fn_requires_f1.closure.Insts.CoreOpsFunctionFnMutTupleBool.call_mut
  (state : __anodized_fn_requires_f1.closure) (_ : Unit) :
  Result (Bool × __anodized_fn_requires_f1.closure)
  := do
  let b ←
    __anodized_fn_requires_f1.closure.Insts.CoreOpsFunctionFnTupleBool.call
      state ()
  ok (b, state)

/-- [e01::__anodized_fn_requires_f1::{impl core::ops::function::FnOnce<(), bool> for e01::__anodized_fn_requires_f1::closure<'_0>}::call_once]:
    Source: 'examples/e01/src/lib.rs', lines 8:0-8:24 -/
def
  __anodized_fn_requires_f1.closure.Insts.CoreOpsFunctionFnOnceTupleBool.call_once
  (c : __anodized_fn_requires_f1.closure) (_ : Unit) : Result Bool := do
  let (b, _) ←
    __anodized_fn_requires_f1.closure.Insts.CoreOpsFunctionFnMutTupleBool.call_mut
      c ()
  ok b

/-- Trait implementation: [e01::__anodized_fn_requires_f1::{impl core::ops::function::FnOnce<(), bool> for e01::__anodized_fn_requires_f1::closure<'_0>}]
    Source: 'examples/e01/src/lib.rs', lines 8:0-8:24 -/
@[reducible]
def __anodized_fn_requires_f1.closure.Insts.CoreOpsFunctionFnOnceTupleBool :
  core.ops.function.FnOnce __anodized_fn_requires_f1.closure Unit Bool := {
  call_once :=
    __anodized_fn_requires_f1.closure.Insts.CoreOpsFunctionFnOnceTupleBool.call_once
}

/-- Trait implementation: [e01::__anodized_fn_requires_f1::{impl core::ops::function::FnMut<(), bool> for e01::__anodized_fn_requires_f1::closure<'_0>}]
    Source: 'examples/e01/src/lib.rs', lines 8:0-8:24 -/
@[reducible]
def __anodized_fn_requires_f1.closure.Insts.CoreOpsFunctionFnMutTupleBool :
  core.ops.function.FnMut __anodized_fn_requires_f1.closure Unit Bool := {
  FnOnceInst :=
    __anodized_fn_requires_f1.closure.Insts.CoreOpsFunctionFnOnceTupleBool
  call_mut :=
    __anodized_fn_requires_f1.closure.Insts.CoreOpsFunctionFnMutTupleBool.call_mut
}

/-- Trait implementation: [e01::__anodized_fn_requires_f1::{impl core::ops::function::Fn<(), bool> for e01::__anodized_fn_requires_f1::closure<'_0>}]
    Source: 'examples/e01/src/lib.rs', lines 8:0-8:24 -/
@[reducible]
def __anodized_fn_requires_f1.closure.Insts.CoreOpsFunctionFnTupleBool :
  core.ops.function.Fn __anodized_fn_requires_f1.closure Unit Bool := {
  FnMutInst :=
    __anodized_fn_requires_f1.closure.Insts.CoreOpsFunctionFnMutTupleBool
  call :=
    __anodized_fn_requires_f1.closure.Insts.CoreOpsFunctionFnTupleBool.call
}

/-- [e01::__anodized_fn_requires_f1]:
    Source: 'examples/e01/src/lib.rs', lines 8:0-8:24 -/
def __anodized_fn_requires_f1 (x : Std.U8) : Result Bool := do
  __anodized_fn_requires_f1.closure.Insts.CoreOpsFunctionFnTupleBool.call x ()

/-- [e01::__anodized_fn_ensures_f1]:
    Source: 'examples/e01/src/lib.rs', lines 8:0-8:24 -/
def __anodized_fn_ensures_f1 (x : Std.U8) (_ : Unit) : Result Bool := do
  ok true

/-- [e01::__anodized_fn_qualifiers_f1]
    Source: 'examples/e01/src/lib.rs', lines 8:0-8:24 -/
@[global_simps, irreducible] def __anodized_fn_qualifiers_f1 : Std.U32 := 0#u32

/-- [e01::f1]:
    Source: 'examples/e01/src/lib.rs', lines 9:0-9:19
    Visibility: public -/
def f1 (x : Std.U8) : Result Unit := do
  ok ()

/-- [e01::__anodized_fn_ensures_f2::{impl core::ops::function::Fn<(&'_ u8,), bool> for e01::__anodized_fn_ensures_f2::closure}::call]:
    Source: 'examples/e01/src/lib.rs', lines 11:0-11:30 -/
def
  __anodized_fn_ensures_f2.closure.Insts.CoreOpsFunctionFnTupleSharedU8Bool.call
  (c : __anodized_fn_ensures_f2.closure) (tupled_args : Std.U8) :
  Result Bool
  := do
  ok (tupled_args = 1#u8)

/-- [e01::__anodized_fn_ensures_f2::{impl core::ops::function::FnMut<(&'_ u8,), bool> for e01::__anodized_fn_ensures_f2::closure}::call_mut]:
    Source: 'examples/e01/src/lib.rs', lines 11:0-11:30 -/
def
  __anodized_fn_ensures_f2.closure.Insts.CoreOpsFunctionFnMutTupleSharedU8Bool.call_mut
  (state : __anodized_fn_ensures_f2.closure) (args : Std.U8) :
  Result (Bool × __anodized_fn_ensures_f2.closure)
  := do
  let b ←
    __anodized_fn_ensures_f2.closure.Insts.CoreOpsFunctionFnTupleSharedU8Bool.call
      state args
  ok (b, state)

/-- [e01::__anodized_fn_ensures_f2::{impl core::ops::function::FnOnce<(&'_ u8,), bool> for e01::__anodized_fn_ensures_f2::closure}::call_once]:
    Source: 'examples/e01/src/lib.rs', lines 11:0-11:30 -/
def
  __anodized_fn_ensures_f2.closure.Insts.CoreOpsFunctionFnOnceTupleSharedU8Bool.call_once
  (c : __anodized_fn_ensures_f2.closure) (i : Std.U8) : Result Bool := do
  let (b, _) ←
    __anodized_fn_ensures_f2.closure.Insts.CoreOpsFunctionFnMutTupleSharedU8Bool.call_mut
      c i
  ok b

/-- Trait implementation: [e01::__anodized_fn_ensures_f2::{impl core::ops::function::FnOnce<(&'_ u8,), bool> for e01::__anodized_fn_ensures_f2::closure}]
    Source: 'examples/e01/src/lib.rs', lines 11:0-11:30 -/
@[reducible]
def
  __anodized_fn_ensures_f2.closure.Insts.CoreOpsFunctionFnOnceTupleSharedU8Bool
  : core.ops.function.FnOnce __anodized_fn_ensures_f2.closure Std.U8 Bool := {
  call_once :=
    __anodized_fn_ensures_f2.closure.Insts.CoreOpsFunctionFnOnceTupleSharedU8Bool.call_once
}

/-- Trait implementation: [e01::__anodized_fn_ensures_f2::{impl core::ops::function::FnMut<(&'_ u8,), bool> for e01::__anodized_fn_ensures_f2::closure}]
    Source: 'examples/e01/src/lib.rs', lines 11:0-11:30 -/
@[reducible]
def
  __anodized_fn_ensures_f2.closure.Insts.CoreOpsFunctionFnMutTupleSharedU8Bool
  : core.ops.function.FnMut __anodized_fn_ensures_f2.closure Std.U8 Bool := {
  FnOnceInst :=
    __anodized_fn_ensures_f2.closure.Insts.CoreOpsFunctionFnOnceTupleSharedU8Bool
  call_mut :=
    __anodized_fn_ensures_f2.closure.Insts.CoreOpsFunctionFnMutTupleSharedU8Bool.call_mut
}

/-- Trait implementation: [e01::__anodized_fn_ensures_f2::{impl core::ops::function::Fn<(&'_ u8,), bool> for e01::__anodized_fn_ensures_f2::closure}]
    Source: 'examples/e01/src/lib.rs', lines 11:0-11:30 -/
@[reducible]
def __anodized_fn_ensures_f2.closure.Insts.CoreOpsFunctionFnTupleSharedU8Bool :
  core.ops.function.Fn __anodized_fn_ensures_f2.closure Std.U8 Bool := {
  FnMutInst :=
    __anodized_fn_ensures_f2.closure.Insts.CoreOpsFunctionFnMutTupleSharedU8Bool
  call :=
    __anodized_fn_ensures_f2.closure.Insts.CoreOpsFunctionFnTupleSharedU8Bool.call
}

/-- [e01::__anodized_fn_requires_f2]:
    Source: 'examples/e01/src/lib.rs', lines 11:0-11:30 -/
def __anodized_fn_requires_f2 : Result Bool := do
  ok true

/-- [e01::__anodized_fn_ensures_f2]:
    Source: 'examples/e01/src/lib.rs', lines 11:0-11:30 -/
def __anodized_fn_ensures_f2 (__anodized_output : Std.U8) : Result Bool := do
  __anodized_fn_ensures_f2.closure.Insts.CoreOpsFunctionFnTupleSharedU8Bool.call
    () __anodized_output

/-- [e01::__anodized_fn_qualifiers_f2]
    Source: 'examples/e01/src/lib.rs', lines 11:0-11:30 -/
@[global_simps, irreducible] def __anodized_fn_qualifiers_f2 : Std.U32 := 0#u32

/-- [e01::f2]:
    Source: 'examples/e01/src/lib.rs', lines 12:0-14:1
    Visibility: public -/
def f2 : Result Std.U8 := do
  ok 1#u8

/-- [e01::T::__anodized_fn_requires_f3::{impl core::ops::function::Fn<(), bool> for e01::T::__anodized_fn_requires_f3::closure<'_0, Self>}::call]:
    Source: 'examples/e01/src/lib.rs', lines 18:0-18:7 -/
def T.__anodized_fn_requires_f3.closure.Insts.CoreOpsFunctionFnTupleBool.call
  {Self : Type} (TInst : T Self) (c : T.__anodized_fn_requires_f3.closure Self)
  (_ : Unit) :
  Result Bool
  := do
  ok (c > 0#u8)

/-- [e01::T::__anodized_fn_requires_f3::{impl core::ops::function::FnMut<(), bool> for e01::T::__anodized_fn_requires_f3::closure<'_0, Self>}::call_mut]:
    Source: 'examples/e01/src/lib.rs', lines 18:0-18:7 -/
def
  T.__anodized_fn_requires_f3.closure.Insts.CoreOpsFunctionFnMutTupleBool.call_mut
  {Self : Type} (TInst : T Self)
  (state : T.__anodized_fn_requires_f3.closure Self) (_ : Unit) :
  Result (Bool × (T.__anodized_fn_requires_f3.closure Self))
  := do
  let b ←
    T.__anodized_fn_requires_f3.closure.Insts.CoreOpsFunctionFnTupleBool.call
      TInst state ()
  ok (b, state)

/-- [e01::T::__anodized_fn_requires_f3::{impl core::ops::function::FnOnce<(), bool> for e01::T::__anodized_fn_requires_f3::closure<'_0, Self>}::call_once]:
    Source: 'examples/e01/src/lib.rs', lines 18:0-18:7 -/
def
  T.__anodized_fn_requires_f3.closure.Insts.CoreOpsFunctionFnOnceTupleBool.call_once
  {Self : Type} (TInst : T Self) (c : T.__anodized_fn_requires_f3.closure Self)
  (_ : Unit) :
  Result Bool
  := do
  let (b, _) ←
    T.__anodized_fn_requires_f3.closure.Insts.CoreOpsFunctionFnMutTupleBool.call_mut
      TInst c ()
  ok b

/-- Trait implementation: [e01::T::__anodized_fn_requires_f3::{impl core::ops::function::FnOnce<(), bool> for e01::T::__anodized_fn_requires_f3::closure<'_0, Self>}]
    Source: 'examples/e01/src/lib.rs', lines 18:0-18:7 -/
@[reducible]
def T.__anodized_fn_requires_f3.closure.Insts.CoreOpsFunctionFnOnceTupleBool
  {Self : Type} (TInst : T Self) : core.ops.function.FnOnce
  (T.__anodized_fn_requires_f3.closure Self) Unit Bool := {
  call_once :=
    T.__anodized_fn_requires_f3.closure.Insts.CoreOpsFunctionFnOnceTupleBool.call_once
    TInst
}

/-- Trait implementation: [e01::T::__anodized_fn_requires_f3::{impl core::ops::function::FnMut<(), bool> for e01::T::__anodized_fn_requires_f3::closure<'_0, Self>}]
    Source: 'examples/e01/src/lib.rs', lines 18:0-18:7 -/
@[reducible]
def T.__anodized_fn_requires_f3.closure.Insts.CoreOpsFunctionFnMutTupleBool
  {Self : Type} (TInst : T Self) : core.ops.function.FnMut
  (T.__anodized_fn_requires_f3.closure Self) Unit Bool := {
  FnOnceInst :=
    T.__anodized_fn_requires_f3.closure.Insts.CoreOpsFunctionFnOnceTupleBool
    TInst
  call_mut :=
    T.__anodized_fn_requires_f3.closure.Insts.CoreOpsFunctionFnMutTupleBool.call_mut
    TInst
}

/-- Trait implementation: [e01::T::__anodized_fn_requires_f3::{impl core::ops::function::Fn<(), bool> for e01::T::__anodized_fn_requires_f3::closure<'_0, Self>}]
    Source: 'examples/e01/src/lib.rs', lines 18:0-18:7 -/
@[reducible]
def T.__anodized_fn_requires_f3.closure.Insts.CoreOpsFunctionFnTupleBool {Self
  : Type} (TInst : T Self) : core.ops.function.Fn
  (T.__anodized_fn_requires_f3.closure Self) Unit Bool := {
  FnMutInst :=
    T.__anodized_fn_requires_f3.closure.Insts.CoreOpsFunctionFnMutTupleBool
    TInst
  call :=
    T.__anodized_fn_requires_f3.closure.Insts.CoreOpsFunctionFnTupleBool.call
    TInst
}

/-- [e01::T::__anodized_fn_ensures_f3::{impl core::ops::function::Fn<(&'_ u8,), bool> for e01::T::__anodized_fn_ensures_f3::closure<Self>}::call]:
    Source: 'examples/e01/src/lib.rs', lines 18:0-18:7 -/
def
  T.__anodized_fn_ensures_f3.closure.Insts.CoreOpsFunctionFnTupleSharedU8Bool.call
  {Self : Type} (TInst : T Self) (c : T.__anodized_fn_ensures_f3.closure Self)
  (tupled_args : Std.U8) :
  Result Bool
  := do
  ok (tupled_args > 0#u8)

/-- [e01::T::__anodized_fn_ensures_f3::{impl core::ops::function::FnMut<(&'_ u8,), bool> for e01::T::__anodized_fn_ensures_f3::closure<Self>}::call_mut]:
    Source: 'examples/e01/src/lib.rs', lines 18:0-18:7 -/
def
  T.__anodized_fn_ensures_f3.closure.Insts.CoreOpsFunctionFnMutTupleSharedU8Bool.call_mut
  {Self : Type} (TInst : T Self)
  (state : T.__anodized_fn_ensures_f3.closure Self) (args : Std.U8) :
  Result (Bool × (T.__anodized_fn_ensures_f3.closure Self))
  := do
  let b ←
    T.__anodized_fn_ensures_f3.closure.Insts.CoreOpsFunctionFnTupleSharedU8Bool.call
      TInst state args
  ok (b, state)

/-- [e01::T::__anodized_fn_ensures_f3::{impl core::ops::function::FnOnce<(&'_ u8,), bool> for e01::T::__anodized_fn_ensures_f3::closure<Self>}::call_once]:
    Source: 'examples/e01/src/lib.rs', lines 18:0-18:7 -/
def
  T.__anodized_fn_ensures_f3.closure.Insts.CoreOpsFunctionFnOnceTupleSharedU8Bool.call_once
  {Self : Type} (TInst : T Self) (c : T.__anodized_fn_ensures_f3.closure Self)
  (i : Std.U8) :
  Result Bool
  := do
  let (b, _) ←
    T.__anodized_fn_ensures_f3.closure.Insts.CoreOpsFunctionFnMutTupleSharedU8Bool.call_mut
      TInst c i
  ok b

/-- Trait implementation: [e01::T::__anodized_fn_ensures_f3::{impl core::ops::function::FnOnce<(&'_ u8,), bool> for e01::T::__anodized_fn_ensures_f3::closure<Self>}]
    Source: 'examples/e01/src/lib.rs', lines 18:0-18:7 -/
@[reducible]
def
  T.__anodized_fn_ensures_f3.closure.Insts.CoreOpsFunctionFnOnceTupleSharedU8Bool
  {Self : Type} (TInst : T Self) : core.ops.function.FnOnce
  (T.__anodized_fn_ensures_f3.closure Self) Std.U8 Bool := {
  call_once :=
    T.__anodized_fn_ensures_f3.closure.Insts.CoreOpsFunctionFnOnceTupleSharedU8Bool.call_once
    TInst
}

/-- Trait implementation: [e01::T::__anodized_fn_ensures_f3::{impl core::ops::function::FnMut<(&'_ u8,), bool> for e01::T::__anodized_fn_ensures_f3::closure<Self>}]
    Source: 'examples/e01/src/lib.rs', lines 18:0-18:7 -/
@[reducible]
def
  T.__anodized_fn_ensures_f3.closure.Insts.CoreOpsFunctionFnMutTupleSharedU8Bool
  {Self : Type} (TInst : T Self) : core.ops.function.FnMut
  (T.__anodized_fn_ensures_f3.closure Self) Std.U8 Bool := {
  FnOnceInst :=
    T.__anodized_fn_ensures_f3.closure.Insts.CoreOpsFunctionFnOnceTupleSharedU8Bool
    TInst
  call_mut :=
    T.__anodized_fn_ensures_f3.closure.Insts.CoreOpsFunctionFnMutTupleSharedU8Bool.call_mut
    TInst
}

/-- Trait implementation: [e01::T::__anodized_fn_ensures_f3::{impl core::ops::function::Fn<(&'_ u8,), bool> for e01::T::__anodized_fn_ensures_f3::closure<Self>}]
    Source: 'examples/e01/src/lib.rs', lines 18:0-18:7 -/
@[reducible]
def T.__anodized_fn_ensures_f3.closure.Insts.CoreOpsFunctionFnTupleSharedU8Bool
  {Self : Type} (TInst : T Self) : core.ops.function.Fn
  (T.__anodized_fn_ensures_f3.closure Self) Std.U8 Bool := {
  FnMutInst :=
    T.__anodized_fn_ensures_f3.closure.Insts.CoreOpsFunctionFnMutTupleSharedU8Bool
    TInst
  call :=
    T.__anodized_fn_ensures_f3.closure.Insts.CoreOpsFunctionFnTupleSharedU8Bool.call
    TInst
}

/-- [e01::T::__anodized_fn_requires_f3]:
    Source: 'examples/e01/src/lib.rs', lines 18:0-18:7
    Visibility: public -/
def T.__anodized_fn_requires_f3.default
  {Self : Type} (TInst : T Self) (x : Std.U8) : Result Bool := do
  T.__anodized_fn_requires_f3.closure.Insts.CoreOpsFunctionFnTupleBool.call
    TInst x ()

/-- [e01::T::__anodized_fn_ensures_f3]:
    Source: 'examples/e01/src/lib.rs', lines 18:0-18:7
    Visibility: public -/
def T.__anodized_fn_ensures_f3.default
  {Self : Type} (TInst : T Self) (x : Std.U8) (__anodized_output : Std.U8) :
  Result Bool
  := do
  T.__anodized_fn_ensures_f3.closure.Insts.CoreOpsFunctionFnTupleSharedU8Bool.call
    TInst () __anodized_output

/-- [e01::T::__anodized_fn_qualifiers_trait_f3]
    Source: 'examples/e01/src/lib.rs', lines 18:0-18:7
    Visibility: public -/
@[global_simps, irreducible, trait_default]
def T.__anodized_fn_qualifiers_trait_f3.default (Self : Type) : Std.U32 :=
  0#u32

/-- [e01::T::__anodized_fn_qualifiers_f3]
    Source: 'examples/e01/src/lib.rs', lines 18:0-18:7
    Visibility: public -/
@[global_simps, irreducible, trait_default]
def T.__anodized_fn_qualifiers_f3.default (Self : Type) : Std.U32 := 0#u32

/-- [e01::{impl e01::T for u8}::__anodized_fn_requires_f3::{impl core::ops::function::Fn<(), bool> for e01::{impl e01::T for u8}::__anodized_fn_requires_f3::closure}::call]:
    Source: 'examples/e01/src/lib.rs', lines 27:0-27:7 -/
def TU8.__anodized_fn_requires_f3.closure.Insts.CoreOpsFunctionFnTupleBool.call
  (c : TU8.__anodized_fn_requires_f3.closure) (_ : Unit) : Result Bool := do
  ok true

/-- [e01::{impl e01::T for u8}::__anodized_fn_requires_f3::{impl core::ops::function::FnMut<(), bool> for e01::{impl e01::T for u8}::__anodized_fn_requires_f3::closure}::call_mut]:
    Source: 'examples/e01/src/lib.rs', lines 27:0-27:7 -/
def
  TU8.__anodized_fn_requires_f3.closure.Insts.CoreOpsFunctionFnMutTupleBool.call_mut
  (state : TU8.__anodized_fn_requires_f3.closure) (_ : Unit) :
  Result (Bool × TU8.__anodized_fn_requires_f3.closure)
  := do
  let b ←
    TU8.__anodized_fn_requires_f3.closure.Insts.CoreOpsFunctionFnTupleBool.call
      state ()
  ok (b, state)

/-- [e01::{impl e01::T for u8}::__anodized_fn_requires_f3::{impl core::ops::function::FnOnce<(), bool> for e01::{impl e01::T for u8}::__anodized_fn_requires_f3::closure}::call_once]:
    Source: 'examples/e01/src/lib.rs', lines 27:0-27:7 -/
def
  TU8.__anodized_fn_requires_f3.closure.Insts.CoreOpsFunctionFnOnceTupleBool.call_once
  (c : TU8.__anodized_fn_requires_f3.closure) (_ : Unit) : Result Bool := do
  let (b, _) ←
    TU8.__anodized_fn_requires_f3.closure.Insts.CoreOpsFunctionFnMutTupleBool.call_mut
      c ()
  ok b

/-- Trait implementation: [e01::{impl e01::T for u8}::__anodized_fn_requires_f3::{impl core::ops::function::FnOnce<(), bool> for e01::{impl e01::T for u8}::__anodized_fn_requires_f3::closure}]
    Source: 'examples/e01/src/lib.rs', lines 27:0-27:7 -/
@[reducible]
def TU8.__anodized_fn_requires_f3.closure.Insts.CoreOpsFunctionFnOnceTupleBool
  : core.ops.function.FnOnce TU8.__anodized_fn_requires_f3.closure Unit Bool
  := {
  call_once :=
    TU8.__anodized_fn_requires_f3.closure.Insts.CoreOpsFunctionFnOnceTupleBool.call_once
}

/-- Trait implementation: [e01::{impl e01::T for u8}::__anodized_fn_requires_f3::{impl core::ops::function::FnMut<(), bool> for e01::{impl e01::T for u8}::__anodized_fn_requires_f3::closure}]
    Source: 'examples/e01/src/lib.rs', lines 27:0-27:7 -/
@[reducible]
def TU8.__anodized_fn_requires_f3.closure.Insts.CoreOpsFunctionFnMutTupleBool :
  core.ops.function.FnMut TU8.__anodized_fn_requires_f3.closure Unit Bool := {
  FnOnceInst :=
    TU8.__anodized_fn_requires_f3.closure.Insts.CoreOpsFunctionFnOnceTupleBool
  call_mut :=
    TU8.__anodized_fn_requires_f3.closure.Insts.CoreOpsFunctionFnMutTupleBool.call_mut
}

/-- Trait implementation: [e01::{impl e01::T for u8}::__anodized_fn_requires_f3::{impl core::ops::function::Fn<(), bool> for e01::{impl e01::T for u8}::__anodized_fn_requires_f3::closure}]
    Source: 'examples/e01/src/lib.rs', lines 27:0-27:7 -/
@[reducible]
def TU8.__anodized_fn_requires_f3.closure.Insts.CoreOpsFunctionFnTupleBool :
  core.ops.function.Fn TU8.__anodized_fn_requires_f3.closure Unit Bool := {
  FnMutInst :=
    TU8.__anodized_fn_requires_f3.closure.Insts.CoreOpsFunctionFnMutTupleBool
  call :=
    TU8.__anodized_fn_requires_f3.closure.Insts.CoreOpsFunctionFnTupleBool.call
}

/-- [e01::{impl e01::T for u8}::__anodized_fn_ensures_f3::{impl core::ops::function::Fn<(&'_ u8,), bool> for e01::{impl e01::T for u8}::__anodized_fn_ensures_f3::closure}::call]:
    Source: 'examples/e01/src/lib.rs', lines 27:0-27:7 -/
def
  TU8.__anodized_fn_ensures_f3.closure.Insts.CoreOpsFunctionFnTupleSharedU8Bool.call
  (c : TU8.__anodized_fn_ensures_f3.closure) (tupled_args : Std.U8) :
  Result Bool
  := do
  ok (tupled_args > 1#u8)

/-- [e01::{impl e01::T for u8}::__anodized_fn_ensures_f3::{impl core::ops::function::FnMut<(&'_ u8,), bool> for e01::{impl e01::T for u8}::__anodized_fn_ensures_f3::closure}::call_mut]:
    Source: 'examples/e01/src/lib.rs', lines 27:0-27:7 -/
def
  TU8.__anodized_fn_ensures_f3.closure.Insts.CoreOpsFunctionFnMutTupleSharedU8Bool.call_mut
  (state : TU8.__anodized_fn_ensures_f3.closure) (args : Std.U8) :
  Result (Bool × TU8.__anodized_fn_ensures_f3.closure)
  := do
  let b ←
    TU8.__anodized_fn_ensures_f3.closure.Insts.CoreOpsFunctionFnTupleSharedU8Bool.call
      state args
  ok (b, state)

/-- [e01::{impl e01::T for u8}::__anodized_fn_ensures_f3::{impl core::ops::function::FnOnce<(&'_ u8,), bool> for e01::{impl e01::T for u8}::__anodized_fn_ensures_f3::closure}::call_once]:
    Source: 'examples/e01/src/lib.rs', lines 27:0-27:7 -/
def
  TU8.__anodized_fn_ensures_f3.closure.Insts.CoreOpsFunctionFnOnceTupleSharedU8Bool.call_once
  (c : TU8.__anodized_fn_ensures_f3.closure) (i : Std.U8) : Result Bool := do
  let (b, _) ←
    TU8.__anodized_fn_ensures_f3.closure.Insts.CoreOpsFunctionFnMutTupleSharedU8Bool.call_mut
      c i
  ok b

/-- Trait implementation: [e01::{impl e01::T for u8}::__anodized_fn_ensures_f3::{impl core::ops::function::FnOnce<(&'_ u8,), bool> for e01::{impl e01::T for u8}::__anodized_fn_ensures_f3::closure}]
    Source: 'examples/e01/src/lib.rs', lines 27:0-27:7 -/
@[reducible]
def
  TU8.__anodized_fn_ensures_f3.closure.Insts.CoreOpsFunctionFnOnceTupleSharedU8Bool
  : core.ops.function.FnOnce TU8.__anodized_fn_ensures_f3.closure Std.U8 Bool
  := {
  call_once :=
    TU8.__anodized_fn_ensures_f3.closure.Insts.CoreOpsFunctionFnOnceTupleSharedU8Bool.call_once
}

/-- Trait implementation: [e01::{impl e01::T for u8}::__anodized_fn_ensures_f3::{impl core::ops::function::FnMut<(&'_ u8,), bool> for e01::{impl e01::T for u8}::__anodized_fn_ensures_f3::closure}]
    Source: 'examples/e01/src/lib.rs', lines 27:0-27:7 -/
@[reducible]
def
  TU8.__anodized_fn_ensures_f3.closure.Insts.CoreOpsFunctionFnMutTupleSharedU8Bool
  : core.ops.function.FnMut TU8.__anodized_fn_ensures_f3.closure Std.U8 Bool
  := {
  FnOnceInst :=
    TU8.__anodized_fn_ensures_f3.closure.Insts.CoreOpsFunctionFnOnceTupleSharedU8Bool
  call_mut :=
    TU8.__anodized_fn_ensures_f3.closure.Insts.CoreOpsFunctionFnMutTupleSharedU8Bool.call_mut
}

/-- Trait implementation: [e01::{impl e01::T for u8}::__anodized_fn_ensures_f3::{impl core::ops::function::Fn<(&'_ u8,), bool> for e01::{impl e01::T for u8}::__anodized_fn_ensures_f3::closure}]
    Source: 'examples/e01/src/lib.rs', lines 27:0-27:7 -/
@[reducible]
def
  TU8.__anodized_fn_ensures_f3.closure.Insts.CoreOpsFunctionFnTupleSharedU8Bool
  : core.ops.function.Fn TU8.__anodized_fn_ensures_f3.closure Std.U8 Bool := {
  FnMutInst :=
    TU8.__anodized_fn_ensures_f3.closure.Insts.CoreOpsFunctionFnMutTupleSharedU8Bool
  call :=
    TU8.__anodized_fn_ensures_f3.closure.Insts.CoreOpsFunctionFnTupleSharedU8Bool.call
}

/-- [e01::{impl e01::T for u8}::__anodized_fn_requires_f3]:
    Source: 'examples/e01/src/lib.rs', lines 27:0-27:7
    Visibility: public -/
def U8.Insts.E01T.__anodized_fn_requires_f3 (x : Std.U8) : Result Bool := do
  TU8.__anodized_fn_requires_f3.closure.Insts.CoreOpsFunctionFnTupleBool.call
    () ()

/-- [e01::{impl e01::T for u8}::__anodized_fn_ensures_f3]:
    Source: 'examples/e01/src/lib.rs', lines 27:0-27:7
    Visibility: public -/
def U8.Insts.E01T.__anodized_fn_ensures_f3
  (x : Std.U8) (__anodized_output : Std.U8) : Result Bool := do
  TU8.__anodized_fn_ensures_f3.closure.Insts.CoreOpsFunctionFnTupleSharedU8Bool.call
    () __anodized_output

/-- [e01::{impl e01::T for u8}::__anodized_fn_qualifiers_f3]
    Source: 'examples/e01/src/lib.rs', lines 27:0-27:7
    Visibility: public -/
@[global_simps, irreducible]
def U8.Insts.E01T.__anodized_fn_qualifiers_f3 : Std.U32 := 0#u32

/-- [e01::{impl e01::T for u8}::f3]:
    Source: 'examples/e01/src/lib.rs', lines 33:4-35:5
    Visibility: public -/
def U8.Insts.E01T.f3 (x : Std.U8) : Result Std.U8 := do
  ok 2#u8

/-- Trait implementation: [e01::{impl e01::T for u8}]
    Source: 'examples/e01/src/lib.rs', lines 28:0-36:1 -/
@[reducible]
def U8.Insts.E01T : T Std.U8 := {
  __anodized_fn_qualifiers_trait_f3 := ok
    (T.__anodized_fn_qualifiers_trait_f3.default Std.U8)
  __anodized_fn_qualifiers_f3 := ok U8.Insts.E01T.__anodized_fn_qualifiers_f3
  __anodized_fn_requires_f3 := U8.Insts.E01T.__anodized_fn_requires_f3
  __anodized_fn_ensures_f3 := U8.Insts.E01T.__anodized_fn_ensures_f3
  f3 := U8.Insts.E01T.f3
}

/-- [e01::f_loop]: loop body 0:
    Source: 'examples/e01/src/lib.rs', lines 48:4-52:5
    Visibility: public -/
@[rust_loop_body]
def f_loop_loop.body
  (x : Slice Std.U8) (iter : core.ops.range.Range Std.Usize) (max : Std.U8) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × Std.U8) Std.U8)
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done max)
  | some i =>
    let i1 ← Slice.index_usize x i
    if i1 > max
    then ok (cont (iter1, i1))
    else ok (cont (iter1, max))

/-- [e01::f_loop]: loop 0:
    Source: 'examples/e01/src/lib.rs', lines 48:4-52:5
    Visibility: public -/
@[rust_loop]
def f_loop_loop
  (iter : core.ops.range.Range Std.Usize) (x : Slice Std.U8) (max : Std.U8) :
  Result Std.U8
  := do
  loop
    (fun (iter1, max1) => f_loop_loop.body x iter1 max1)
    (iter, max)

/-- [e01::f_loop]:
    Source: 'examples/e01/src/lib.rs', lines 43:0-54:1
    Visibility: public -/
def f_loop (x : Slice Std.U8) : Result Std.U8 := do
  let i := Slice.len x
  f_loop_loop { start := 0#usize, «end» := i } x 0#u8

/-- [e01::f_while]: loop body 0:
    Source: 'examples/e01/src/lib.rs', lines 71:4-76:5
    Visibility: public -/
@[rust_loop_body]
def f_while_loop.body
  (x : Slice Std.U8) (max : Std.U8) (i : Std.Usize) :
  Result (ControlFlow (Std.U8 × Std.Usize) Std.U8)
  := do
  let i1 := Slice.len x
  if i < i1
  then
    let i2 ← Slice.index_usize x i
    let max1 ← if i2 > max
                 then ok i2
                 else ok max
    let i3 ← i + 1#usize
    ok (cont (max1, i3))
  else ok (done max)

/-- [e01::f_while]: loop 0:
    Source: 'examples/e01/src/lib.rs', lines 71:4-76:5
    Visibility: public -/
@[rust_loop]
def f_while_loop
  (x : Slice Std.U8) (max : Std.U8) (i : Std.Usize) : Result Std.U8 := do
  loop
    (fun (max1, i1) => f_while_loop.body x max1 i1)
    (max, i)

/-- [e01::f_while]:
    Source: 'examples/e01/src/lib.rs', lines 61:0-78:1
    Visibility: public -/
@[reducible]
def f_while (x : Slice Std.U8) : Result Std.U8 := do
  f_while_loop x 0#u8 0#usize

/-- [e01::{e01::S}::__anodized_data_maintains::{impl core::ops::function::Fn<(), bool> for e01::{e01::S}::__anodized_data_maintains::closure<'_0>}::call]:
    Source: 'examples/e01/src/lib.rs', lines 82:0-84:2 -/
def S.__anodized_data_maintains.closure.Insts.CoreOpsFunctionFnTupleBool.call
  (c : S.__anodized_data_maintains.closure) (_ : Unit) : Result Bool := do
  ok (c.x > 0#u8)

/-- [e01::{e01::S}::__anodized_data_maintains::{impl core::ops::function::FnMut<(), bool> for e01::{e01::S}::__anodized_data_maintains::closure<'_0>}::call_mut]:
    Source: 'examples/e01/src/lib.rs', lines 82:0-84:2 -/
def
  S.__anodized_data_maintains.closure.Insts.CoreOpsFunctionFnMutTupleBool.call_mut
  (state : S.__anodized_data_maintains.closure) (_ : Unit) :
  Result (Bool × S.__anodized_data_maintains.closure)
  := do
  let b ←
    S.__anodized_data_maintains.closure.Insts.CoreOpsFunctionFnTupleBool.call
      state ()
  ok (b, state)

/-- [e01::{e01::S}::__anodized_data_maintains::{impl core::ops::function::FnOnce<(), bool> for e01::{e01::S}::__anodized_data_maintains::closure<'_0>}::call_once]:
    Source: 'examples/e01/src/lib.rs', lines 82:0-84:2 -/
def
  S.__anodized_data_maintains.closure.Insts.CoreOpsFunctionFnOnceTupleBool.call_once
  (c : S.__anodized_data_maintains.closure) (_ : Unit) : Result Bool := do
  let (b, _) ←
    S.__anodized_data_maintains.closure.Insts.CoreOpsFunctionFnMutTupleBool.call_mut
      c ()
  ok b

/-- Trait implementation: [e01::{e01::S}::__anodized_data_maintains::{impl core::ops::function::FnOnce<(), bool> for e01::{e01::S}::__anodized_data_maintains::closure<'_0>}]
    Source: 'examples/e01/src/lib.rs', lines 82:0-84:2 -/
@[reducible]
def S.__anodized_data_maintains.closure.Insts.CoreOpsFunctionFnOnceTupleBool :
  core.ops.function.FnOnce S.__anodized_data_maintains.closure Unit Bool := {
  call_once :=
    S.__anodized_data_maintains.closure.Insts.CoreOpsFunctionFnOnceTupleBool.call_once
}

/-- Trait implementation: [e01::{e01::S}::__anodized_data_maintains::{impl core::ops::function::FnMut<(), bool> for e01::{e01::S}::__anodized_data_maintains::closure<'_0>}]
    Source: 'examples/e01/src/lib.rs', lines 82:0-84:2 -/
@[reducible]
def S.__anodized_data_maintains.closure.Insts.CoreOpsFunctionFnMutTupleBool :
  core.ops.function.FnMut S.__anodized_data_maintains.closure Unit Bool := {
  FnOnceInst :=
    S.__anodized_data_maintains.closure.Insts.CoreOpsFunctionFnOnceTupleBool
  call_mut :=
    S.__anodized_data_maintains.closure.Insts.CoreOpsFunctionFnMutTupleBool.call_mut
}

/-- Trait implementation: [e01::{e01::S}::__anodized_data_maintains::{impl core::ops::function::Fn<(), bool> for e01::{e01::S}::__anodized_data_maintains::closure<'_0>}]
    Source: 'examples/e01/src/lib.rs', lines 82:0-84:2 -/
@[reducible]
def S.__anodized_data_maintains.closure.Insts.CoreOpsFunctionFnTupleBool :
  core.ops.function.Fn S.__anodized_data_maintains.closure Unit Bool := {
  FnMutInst :=
    S.__anodized_data_maintains.closure.Insts.CoreOpsFunctionFnMutTupleBool
  call :=
    S.__anodized_data_maintains.closure.Insts.CoreOpsFunctionFnTupleBool.call
}

/-- [e01::{e01::S}::__anodized_data_maintains]:
    Source: 'examples/e01/src/lib.rs', lines 82:0-84:2 -/
def S.__anodized_data_maintains (self : S) : Result Bool := do
  S.__anodized_data_maintains.closure.Insts.CoreOpsFunctionFnTupleBool.call
    self ()

end e01
