-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [e01]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import examples.e01.translation.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open e01

/-- [core::cmp::impls::{impl core::cmp::PartialOrd<&'_0 B> for &'_1 A}::le]:
    Source: '/rustc/library/core/src/cmp.rs', lines 2145:8-2145:40
    Name pattern: [core::cmp::impls::{core::cmp::PartialOrd<&'1 @A, &'0 @B>}::le]
    Visibility: public -/
@[rust_fun "core::cmp::impls::{core::cmp::PartialOrd<&'1 @A, &'0 @B>}::le"]
axiom Shared1A.Insts.CoreCmpPartialOrdShared0B.le
  {A : Type} {B : Type} (PartialOrdInst : core.cmp.PartialOrd A B) :
  A → B → Result Bool

/-- [core::iter::traits::iterator::Iterator::all]:
    Source: '/rustc/library/core/src/iter/traits/iterator.rs', lines 2831:4-2834:37
    Name pattern: [core::iter::traits::iterator::Iterator::all]
    Visibility: public -/
@[rust_fun "core::iter::traits::iterator::Iterator::all"]
axiom core.iter.traits.iterator.Iterator.all.default
  {Self : Type} {F : Type} {Clause0_Item : Type} (IteratorInst :
  core.iter.traits.iterator.Iterator Self Clause0_Item)
  (opsfunctionFnMutFTupleClause0_ItemBoolInst : core.ops.function.FnMut F
  Clause0_Item Bool) :
  Self → F → Result (Bool × Self)

/-- [core::slice::iter::{impl core::iter::traits::iterator::Iterator<&'a T> for core::slice::iter::Iter<'a, T>}::all]:
    Source: '/rustc/library/core/src/slice/iter/macros.rs', lines 309:12-312:45
    Name pattern: [core::slice::iter::{core::iter::traits::iterator::Iterator<core::slice::iter::Iter<'a, @T>, &'a @T>}::all]
    Visibility: public -/
@[rust_fun
  "core::slice::iter::{core::iter::traits::iterator::Iterator<core::slice::iter::Iter<'a, @T>, &'a @T>}::all"]
axiom core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.all
  {T1 : Type} {F : Type} (opsfunctionFnMutFTupleSharedATBoolInst :
  core.ops.function.FnMut F T1 Bool) :
  core.slice.iter.Iter T1 → F → Result (Bool × (core.slice.iter.Iter T1))

