-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [e01]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace e01

/-- [e01::__anodized_fn_requires_f1::closure]
    Source: 'examples/e01/src/lib.rs', lines 8:0-8:24 -/
@[reducible]
def __anodized_fn_requires_f1.closure := Std.U8

/-- [e01::__anodized_fn_ensures_f2::closure]
    Source: 'examples/e01/src/lib.rs', lines 11:0-11:30 -/
@[reducible]
def __anodized_fn_ensures_f2.closure := Unit

/-- [e01::T::__anodized_fn_requires_f3::closure]
    Source: 'examples/e01/src/lib.rs', lines 18:0-18:7 -/
@[reducible]
def T.__anodized_fn_requires_f3.closure (Self : Type) := Std.U8

/-- [e01::T::__anodized_fn_ensures_f3::closure]
    Source: 'examples/e01/src/lib.rs', lines 18:0-18:7 -/
@[reducible]
def T.__anodized_fn_ensures_f3.closure (Self : Type) := Unit

/-- Trait declaration: [e01::T]
    Source: 'examples/e01/src/lib.rs', lines 19:0-25:1
    Visibility: public -/
structure T (Self : Type) where
  __anodized_fn_qualifiers_trait_f3 : Result Std.U32
  __anodized_fn_qualifiers_f3 : Result Std.U32
  __anodized_fn_requires_f3 : Std.U8 → Result Bool
  __anodized_fn_ensures_f3 : Std.U8 → Std.U8 → Result Bool
  f3 : Std.U8 → Result Std.U8

/-- [e01::{impl e01::T for u8}::__anodized_fn_requires_f3::closure]
    Source: 'examples/e01/src/lib.rs', lines 27:0-27:7 -/
@[reducible]
def TU8.__anodized_fn_requires_f3.closure := Unit

/-- [e01::{impl e01::T for u8}::__anodized_fn_ensures_f3::closure]
    Source: 'examples/e01/src/lib.rs', lines 27:0-27:7 -/
@[reducible]
def TU8.__anodized_fn_ensures_f3.closure := Unit

/-- [e01::S]
    Source: 'examples/e01/src/lib.rs', lines 85:0-87:1
    Visibility: public -/
structure S where
  x : Std.U8

/-- [e01::{e01::S}::__anodized_data_maintains::closure]
    Source: 'examples/e01/src/lib.rs', lines 82:0-84:2 -/
@[reducible]
def S.__anodized_data_maintains.closure := S

end e01
